### ISSUE TITLE
Transactions persisting in History after identity change

### ISSUE THREAD

**Issue by dabura667** [darkwallet/darkwallet#101]
![pic](https://cloud.githubusercontent.com/assets/6586275/2929712/7c47e8b4-d78c-11e3-94c6-6c5714e949dc.PNG)
This is my testnet wallet. When history is done loading (or maybe still loading?) it shows two stealth txes for amounts I have never sent or received, even internally. (I would never set fees like that. and I haven't been sending myself.)

![pic2](https://cloud.githubusercontent.com/assets/6586275/2929727/c6ec31e0-d78c-11e3-8a7e-e3bc38ce1824.PNG)
Here is my empty mainnet wallet. When I switch from All Pockets Addresses or Overview to the history tab, these two txes show for 1 second then disappear. this happens constantly. restarting Chrome and disabling and enabling the plugin don't help.

**Comment by dabura667** [comment]
Found.

These two transactions are funds I sent from spending to savings's stealth address.

However having them show up in my mainnet wallet is still an issue.

**Comment by caedesvvv** [comment]
Can you confirm you still get this in 0.3.1?

**Comment by caedesvvv** [comment]
closing for no feedback. please reopen if you still experience the issue.
