### ISSUE TITLE
When many peers join the browser lags.

### ISSUE THREAD

**Issue by thiswillbeyourusername** [darkwallet/darkwallet#105]
Either it's the long text list of peers which causes it or the multiple peer connections.

Also, a page button for the chat lobby would be nice - yestarday I had hundreds of ASCII penises lagging my browser too.

**Comment by ABISprotocol** [comment]
This is one of the most entertaining projects I have found, ever.  This is here noted entirely apart from its tremendous social value.  Although entertainment is also social value, because if we are not having fun, what are we doing?

**Comment by caedesvvv** [comment]
we made it so now a lot of processing is done on a background thread, should take care of too much lag.
