### ISSUE TITLE
Independently generated tx not being picked up when checking for stealth.

### ISSUE THREAD

**Issue by dabura667** [darkwallet/darkwallet#109]
mainnet txid: bec1ed10bc71d77e1dbefd67e51644bfb73c7461ee2ba88e96199e8a108be606

OP_RET embedded pubkey: 03dab94f5c1c58e698d6d38830b37b449c15cc8456d97ee173c50ce477c6f54bb5
Strip 03 and convert to int: 98931615419397879420873481992872423780348612078113329589492210637441342983093

Method of discovery: In stealth.js I placed 

```
console.log("Ephem pubkey: " + decKey.pub);
```

under the function

```
Stealth.stealthDH = function(e, decKey)
```

(Which when discovering stealth txes, decKey is tx embedded ephem pubkey)

I then proceeded to force stealth multiple times, tried restarting browser, waiting for the processes to calm down, tried again, etc.

I copied each attempt's log completely into a text editor, (I was not missing anything) and I searched for the integer of the embeded pubkey (the x value). (as the output was [x,y] BigInteger pairs)

I didn't get any hits... so I assume that this means DW did not attempt to calculate the shared secret, which means it either wasn't picked up as a stealth tx by DW or I messed up somewhere.

All of the stealth test cases available all work fine for me... but when I generate the tx and send it, it never gets picked up.

One thing I did notice that was different from some of the txes I've sent using testnet was the format of the raw tx.

successful testnet tx:
http://0bin.net/paste/AJF35VJlUdGEY1+r#lrl/i72CKXCh2b4FNwxHv4gYgEac7nsJ+1DTHZNqWsY=

unsuccessful mainnet tx: (The one I spoke of above, includes additional info at bottom)
http://0bin.net/paste/BC6sjOY2fpmSy1WW#mQ8KJij75NeJLLAZWAlQwisqERmfmZ7V3A1T8SCqA9Y=

Perhaps the OP_RETURN not being the first txOut in order is affecting this?

I have been running tests non-stop and they all come up perfectly fine, but when I send the tx DW never picks it up.

Sorry for the long post.

**Comment by caedesvvv** [comment]
have you tried latest git?

we have fixed some issues with stealth reception.

**Comment by caedesvvv** [comment]
oh sorry didn't properly see your report before.

the nonce output has to be right before the paytostealth output, it can't be in other position.

you could redeem the transaction manually but its not standard according to the current spec that says what I write above, the OP_RETURN first, then the paying output. We take special care to produce the outputs like this and also to respect this when mixing outputs.

**Comment by dabura667** [comment]
I attempted again with OP_return first then the stealth send, and it went through and is in my wallet properly.

Thanks!

I think maybe this should be on the wiki for Stealth under "Transaction Format"
