### ISSUE TITLE
add a transaction fee warning

### ISSUE THREAD

**Issue by thiswillbeyourusername** [darkwallet/darkwallet#113]
The idea: If the transaction fee is greater than the amount you're sending - or if it's just an insanely high transaction fee - then give the user a confirmation/warning before it is sent.

This would prevent situations like https://bitcointalk.org/index.php?topic=602152.0 from happening.

I think it's already pretty clear that it's a transaction field, not an amount field. However, it's best to add some kind of protection because if it gets mainstream adoption I'm very certain someone will be stupid enough to enter a transaction fee which empties their entire life savings.

**Comment by ABISprotocol** [comment]
one of the things that could prevent this is ensuring that fees appear clearly in a mainscreen regardless of what wallet is under discussion, but here it is darkwallet and the question is also whether or not the fee is greater than the amount you are sending or is as was shown, "insanely high."  It is possible that this could be addressed by allowing the user to pre-clear a range of fees which are acceptable by the user (understanding that there will be operating defaults from bitcoin but that at the same time the user should be empowered to decide when a wallet is "going out of bounds") but such a preference would be stored locally in the wallet.  However, the fee to be charged for any transaction, to the extent that wallet technology would stipulate it, would show on a primary screen, but still with preferences happening in the background, on the other hand, the confirmation warning may also be relevant in some cases such as a _sound_ or a visual symbol?  Personally I like the idea of a sound alert better.  Something to contemplate further.

**Comment by caedesvvv** [comment]
I agree that we must have a protection from big messups. Also we will show more clear information when sending and confirming the send, now it's just not saying much.. that will be fixed.

**Comment by ABISprotocol** [comment]
thank you @caedesvvv for your response to this issue, I appreciate how concerns are responded to so well in this repository!  Cheers.
