### ISSUE TITLE
Wrong BTC count in pockets

### ISSUE THREAD

**Issue by thiswillbeyourusername** [darkwallet/darkwallet#114]
https://i.imgur.com/W5SLsBj.png

As you can see, "All pockets" calculates the correct total of coins. However, the individual pocket calculation says I have 0.5 BTC.

How it happened: I sent 0.25, it had 1 confirmation, then I closed the browser. I opened the browser again and it gave me the "100% sent coin" notification, I clicked onto the homepage and thats when it gave me the wrong calculation.

**Comment by caedesvvv** [comment]
is this still happening?

**Comment by thiswillbeyourusername** [comment]
I haven't managed to recreate the problem, instead the pending mixer transaction has stalled at 33% for 24hrs.

Update: it might have stalled due to an issue, I sent a transaction from a shared pocket and the other person hasn't verified the transaction, so maybe that's why the new transaction is stalled at 33% (because it's waiting for the previous transaction from shared pocket to be verified?) - or maybe it's just because of the lack of other users with mixing enabled.

**Comment by caedesvvv** [comment]
Ok, about the mixer issue its probably a failed negotiation, we have fixed some bugs that could cause that... best is clear tasks from settings->tools, restart the browser and try again.

**Comment by caedesvvv** [comment]
A lot have changed in showing pocket balance. Please reopen with specific details if you still have any issues.
