### ISSUE TITLE
Negative bitcoin balance when transaction unconfirmed

### ISSUE THREAD

**Issue by jtibble** [darkwallet/darkwallet#119]
![image](https://cloud.githubusercontent.com/assets/2126464/2993139/07b7c64c-dca8-11e3-92c3-a26c37f1bcf1.png)

I sent confirmed bitcoins from one address to another of my addresses, and the UI has stayed in this state for quite some time. In addition, I'm unclear as to 
1. Why the transaction has been unconfirmed for so long now
2. Why the transaction does not appear in my list of transactions
3. How/Why my wallet could be reporting "No coins - 1.2 BTC"

**Comment by dabura667** [comment]
For 3, the panel balances are saying No Coins (that are confirmed) and the - 1.2 BTC means you have sent to another wallet and that send is unconfirmed.

It's the same as the value at the top that says 0 BTC Unconfirmed: -1.2 BTC

**Comment by caedesvvv** [comment]
The negative balance in the second row is the unconfirmed outgoing.

About why it didn't confirm, maybe no fee and fresh coins? We will be adding controls to manage long standind transactions but didn't get around to it yet.

**Comment by caedesvvv** [comment]
Or if you haven't restarted the wallet it's also possible the tx didn't propagate at all, by restarting the  browser it would get freed and you won't see it, if it got propagated the unconfirmed tx will come back from the (bitcoin or testnet) network.

**Comment by caedesvvv** [comment]
ok changed information shown to "Receiving" and "Sending" so this problem should be gone no more negative balances.
