### ISSUE TITLE
Fetch price of bitcoin in other currencies

### ISSUE THREAD

**Issue by sembrestels** [darkwallet/darkwallet#12]
Get data from http://blockchain.info/ticker and show when it is appropriate.

It should be a plug-in (#11).

**Comment by sembrestels** [comment]
For some use cases, it is important to have an average of the price of bitcoin in the time (last week and last month). In order to do it, we can use:

http://blockchain.info/charts/market-price?timespan=30days

And do the average.

**Comment by sembrestels** [comment]
We recently added support for bitcoin avarage. We can close this issue.

**Comment by rdymac** [comment]
Electrum now lets the user select the preferred Exchange Rate from different sources https://github.com/spesmilo/electrum/pull/602#issue-28765173
