### ISSUE TITLE
error connecting/disconected unsystem???

### ISSUE THREAD

**Issue by BnSwiss** [darkwallet/darkwallet#120]
i have been using darkwallet for a while now and have not had any problems but now when i open my wallet i can't connect to unsystem??? the only other issue i've had is last week I sent some money to be mixed but it just sat in mixing so i sent more money and that money went through just fine. that mixing transaction is still sitting there... thats the only thing that I could think of that would cause me to not connect.... but that doesn't make sense really.... please help me i need to send money !!!

**Comment by caedesvvv** [comment]
this was gateway issues, our fault.
