### ISSUE TITLE
popup identity selector dropdown not working

### ISSUE THREAD

**Issue by leafcutterant** [darkwallet/darkwallet#126]
When you click the DW toolbar button, a "quick menu" pops up and you have a button for your own wallet and an "Open wallet" button.

![clipboard01](https://cloud.githubusercontent.com/assets/7106231/3004800/e281c1c4-ddbb-11e3-8c72-aa664b27e4bd.png)

Both takes you to your active wallet, thus "Open wallet" has no functionality and I suggest removing it.

Instead, a button for each existing wallet could be put there, with the active one at the top and the others below it, grayed out, indicating they are inactive. This way one can switch between wallets quickly.

Once logging out will be implemented, a log out button can be put there too.

**Comment by caedesvvv** [comment]
the upper one is going to be a dropdown to select identity, and the bottom one to just go to the current one.

**Comment by caedesvvv** [comment]
renamed the task to reflect what we intend to do.

**Comment by caedesvvv** [comment]
Done in https://github.com/darkwallet/darkwallet/commit/6ef39f60832a1ff6b3f62327ea3ad0f120ed870a

**Comment by leafcutterant** [comment]
Thanks, it's working!
You could as well remove the "Open wallet" button and open the active wallet by simply clicking the right part of the button (leaving the identity selection drop-down for the left part with the arrow).

![clipboard02](https://cloud.githubusercontent.com/assets/7106231/3280743/44de7edc-f47a-11e3-9b8c-09e8265229d1.png)
