### ISSUE TITLE
Multisig -  slider for n of N does not work

### ISSUE THREAD

**Issue by davidgdg** [darkwallet/darkwallet#129]
Hi. Was mucking about trying to create a multi-sig. I entered three valid public keys, but when I tried to slide the slider to choose 2/3 it wouldn't let me. Seems to be stuck on 1/3.
Cheers
David

**Comment by tilthz** [comment]
Hi, are you on the latest version...? there is no slider anymore!

**Comment by davidgdg** [comment]
Lol. Will update. Tnx !
