### ISSUE TITLE
Uncorrectly calculating compressed ECPoint.

### ISSUE THREAD

**Issue by NicolasDorier** [darkwallet/darkwallet#132]
At https://github.com/dabura667/electrum/blob/StealthAddressSend/lib/bitcoin.py#L619
The encoding of the point is not correct (https://bitcointalk.org/index.php?topic=615664.msg6953130#msg6953130)

**Comment by dabura667** [comment]
I think you mean this?

https://github.com/darkwallet/darkwallet/blob/develop/js/util/stealth.js#L42

**Comment by NicolasDorier** [comment]
oups yes that's what I meant.

**Comment by caedesvvv** [comment]
duplicate of #131
