### ISSUE TITLE
Coinjoin failed, transaction was sent without mixing

### ISSUE THREAD

**Issue by sundsta** [darkwallet/darkwallet#133]
There should be an option to not send the transaction if mixing fails.

**Comment by millsdmb** [comment]
+1. possibly default to not send, thus requiring you to resend while
unchecking the coinjoin box.

Regards,
Matt Milsap
203.837.6743 (mobile)

**Comment by leafcutterant** [comment]
Maybe an option at the sending screen for "What to do if mixing fails?" Radiobutton1: don't send and nofity (default) ; Radiobutton2: send anyway.

( @millsdmb your phone number leaks out via your e-mail signature, in case you're concerned.)

**Comment by caedesvvv** [comment]
oops

**Comment by caedesvvv** [comment]
Ok for now we have the 'hard' mixing option that disables behaviour of falling back to sending anyways without mixing. We will be improving actions over ongoing transactions but it's kind of a different task.
