### ISSUE TITLE
Issues/improvements of the new QR code window

### ISSUE THREAD

**Issue by leafcutterant** [darkwallet/darkwallet#140]
Using most recent dev release.
1. There is no background color therefore the text is not visible (see the partially highlighted text in the screenshot). This is not so much an issue with the background, making the text white would solve it and you can even preserve transparency.
2. Upon clicking "Show QR code", we zoom away from the background although I have animations turned off in Settings.
3. Ergonomics idea: right now the QR code window can be closed only via the "X" in the corned, I suggest closing it by clicking anywhere on the background.

![clipboard02](https://cloud.githubusercontent.com/assets/7106231/3280754/33f39232-f47b-11e3-963a-a1ab81b11ab0.png)

**Comment by tilthz** [comment]
Not sure about closing when clicking the background. You can also use the Esc key now. Everything else is already fixed.
