### ISSUE TITLE
The order of pub keys doesn't matter while creating multisig?

### ISSUE THREAD

**Issue by mentica** [darkwallet/darkwallet#146]
Darkwallet creates the same redeemscript no matter the order of the pubkeys.

While using an other tool like pybitcointools, the redeemscript and the escrow address changes depending on the order of pubkeys used to create the redeemscript.
Not sure if this is an issue or not.

**Comment by caedesvvv** [comment]
Yes we create the multisig in canonical order, so we order the pubkeys. Darkwallet will still import unordered multisigs for compatibility with other software, but we produce canonical (the same way we accept uncompressed but produce compressed).

**Comment by nmarley** [comment]
What exactly is "canonical order"? Is there a published standard for pubkey order, or is it just ASCIIbetical order?

**Comment by caedesvvv** [comment]
They get sorted in byte form:

this is done in bitcoinjs-lib, in Script.createMultiSigOutputScript (so it's actually the library we use that does it):

 pubkeys = pubkeys.sort()

I'm not sure this is actually a standard but the idea is you will get the same address if you enter the same keys, no need to worry about the order.
