### ISSUE TITLE
Importing a signed tx for a multisig transaction still shows signed[0/2]

### ISSUE THREAD

**Issue by mentica** [darkwallet/darkwallet#147]
Imported a multisig fund, then used Tools-Import Spend to import a tx that was already signed by 1 key out of the 2 needed (2-of-3)
On the 'tasks' tab it's still shows up as "Signed: [0/2]" and behaves like that as well.

After it was signed again with a foreign key in darkwallet, the tx that is shown in red doesn't change so things like sending it to the other party to sign is impossible.

**Comment by caedesvvv** [comment]
At the moment you need to import the signatures separately, doesn't import it from the transaction (will fix this).

We assume each signs the unsigned transaction, someone collects all signatures and when the last signature is imported the tx is broadcast.

**Comment by caedesvvv** [comment]
Also exporting the transaction will always export the unsigned one (can be changed).

**Comment by dreboli** [comment]
Some escrow providers just sign a tx and releases the half signed tx to the vendor or buyer. The escrow constructs the tx so his fee can be incorporated as an output. (obviously the buyer and the vendor can finalize the transaction without paying this fee too)

Either way it would be nice to have an option to import/export signed, half signed tx-es, I found it useful so far.
