### ISSUE TITLE
Transactions not broadcasting (Mainnet)

### ISSUE THREAD

**Issue by millsdmb** [darkwallet/darkwallet#148]
For the last couple of days when I try to send a transaction it says "broadcasting going slow 0%" for a few times and does nothing.

**Comment by caedesvvv** [comment]
I think the broadcaster was stuck but I might be wrong, anyways after restarting the broadcaster and the gateway it's working.

**Comment by millsdmb** [comment]
​still just says "broadcasting going slow" and nothing happens.​

![image](https://cloud.githubusercontent.com/assets/7471116/3320030/3c0cbd56-f726-11e3-99b7-ac1eeb3ad1ae.png)

![image](https://cloud.githubusercontent.com/assets/7471116/3320035/44cc8534-f726-11e3-978f-99229f51ac88.png)
