### ISSUE TITLE
Viruses or False Positives?

### ISSUE THREAD

**Issue by millsdmb** [darkwallet/darkwallet#151]
just updated the developer branch, my AV is going nuts.

​Malwarebytes Anti-Malware
www.malwarebytes.org​​

Scan Date: 6/20/2014
Scan Time: 2:26:19 PM
Logfile: 
Administrator: Yes

Version: 2.00.2.1012
Malware Database: v2014.06.20.11
Rootkit Database: v2014.06.19.01
License: Premium
Malware Protection: Enabled
Malicious Website Protection: Enabled
Self-protection: Enabled

OS: Windows 8.1
CPU: x64
File System: NTFS

Scan Type: Threat Scan
Result: Completed
Objects Scanned: 272315
Time Elapsed: 13 min, 38 sec

Memory: Enabled
Startup: Enabled
Filesystem: Enabled
Archives: Enabled
Rootkits: Disabled
Heuristics: Enabled
PUP: Warn
PUM: Enabled

Processes: 0
(No malicious items detected)

Modules: 0
(No malicious items detected)

Registry Keys: 0
(No malicious items detected)

Registry Values: 0
(No malicious items detected)

Registry Data: 0
(No malicious items detected)

Folders: 21
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol, , [a5161466ee8dd75fecc9e0c4649e0bf5], 
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0, , [a5161466ee8dd75fecc9e0c4649e0bf5], 
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0\images, , [a5161466ee8dd75fecc9e0c4649e0bf5], 
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0_locales, , [a5161466ee8dd75fecc9e0c4649e0bf5], 
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0_locales\da, , [a5161466ee8dd75fecc9e0c4649e0bf5], 
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0_locales\de, , [a5161466ee8dd75fecc9e0c4649e0bf5], 
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0_locales\en, , [a5161466ee8dd75fecc9e0c4649e0bf5], 
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0_locales\es, , [a5161466ee8dd75fecc9e0c4649e0bf5], 
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0_locales\fi, , [a5161466ee8dd75fecc9e0c4649e0bf5], 
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0_locales\fr, , [a5161466ee8dd75fecc9e0c4649e0bf5], 
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0_locales\id, , [a5161466ee8dd75fecc9e0c4649e0bf5], 
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0_locales\it, , [a5161466ee8dd75fecc9e0c4649e0bf5], 
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0_locales\ja, , [a5161466ee8dd75fecc9e0c4649e0bf5], 
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0_locales\ko, , [a5161466ee8dd75fecc9e0c4649e0bf5], 
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0_locales\nl, , [a5161466ee8dd75fecc9e0c4649e0bf5], 
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0_locales\pl, , [a5161466ee8dd75fecc9e0c4649e0bf5], 
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0_locales\pt_BR, , [a5161466ee8dd75fecc9e0c4649e0bf5], 
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0_locales\ru, , [a5161466ee8dd75fecc9e0c4649e0bf5], 
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0_locales\sv, , [a5161466ee8dd75fecc9e0c4649e0bf5], 
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0_locales\zh_CN, , [a5161466ee8dd75fecc9e0c4649e0bf5], 
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0_locales\zh_TW, , [a5161466ee8dd75fecc9e0c4649e0bf5], 

Files: 19
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0\manifest.json, , [a5161466ee8dd75fecc9e0c4649e0bf5], 
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0\images\en_app_icon-128.png, , [a5161466ee8dd75fecc9e0c4649e0bf5], 
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0_locales\da\messages.json, , [a5161466ee8dd75fecc9e0c4649e0bf5], 
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0_locales\de\messages.json, , [a5161466ee8dd75fecc9e0c4649e0bf5], 
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0_locales\en\messages.json, , [a5161466ee8dd75fecc9e0c4649e0bf5], 
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0_locales\es\messages.json, , [a5161466ee8dd75fecc9e0c4649e0bf5], 
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0_locales\fi\messages.json, , [a5161466ee8dd75fecc9e0c4649e0bf5], 
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0_locales\fr\messages.json, , [a5161466ee8dd75fecc9e0c4649e0bf5], 
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0_locales\id\messages.json, , [a5161466ee8dd75fecc9e0c4649e0bf5], 
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0_locales\it\messages.json, , [a5161466ee8dd75fecc9e0c4649e0bf5], 
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0_locales\ja\messages.json, , [a5161466ee8dd75fecc9e0c4649e0bf5], 
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0_locales\ko\messages.json, , [a5161466ee8dd75fecc9e0c4649e0bf5], 
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0_locales\nl\messages.json, , [a5161466ee8dd75fecc9e0c4649e0bf5], 
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0_locales\pl\messages.json, , [a5161466ee8dd75fecc9e0c4649e0bf5], 
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0_locales\pt_BR\messages.json, , [a5161466ee8dd75fecc9e0c4649e0bf5], 
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0_locales\ru\messages.json, , [a5161466ee8dd75fecc9e0c4649e0bf5], 
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0_locales\sv\messages.json, , [a5161466ee8dd75fecc9e0c4649e0bf5], 
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0_locales\zh_CN\messages.json, , [a5161466ee8dd75fecc9e0c4649e0bf5], 
PUP.Optional.PicEnhance.A, C:\Users\Matt\AppData\Local\Google\Chrome\User Data\Default\Extensions\lbfehkoinhhcknnbdgnnmjhiladcgbol\1.0.8_0_locales\zh_TW\messages.json, , [a5161466ee8dd75fecc9e0c4649e0bf5], 

(end)

**Comment by dabura667** [comment]
Same thing showed up for Evernote's Chrome Extension.
I didn't get it for DarkWallet tho...

Maybe it's an unrelated virus that targets Extensions in Chrome... a new Chrome Extension vulnerability???

http://pastebin.com/wpX5pFv3

This pastebin isn't mine, but I found someone else with the same problem.

**Comment by millsdmb** [comment]
technically they are "potentially unwanted", I wonder if there is a way I
could target it to dark wallet easily. I haven't installed any new ext's
except the developer updates.

I do not want anybody to be given the perception that DW is malicious, with
all the recent negative press regarding chrome exts - hopefully I can help.

**Comment by caedesvvv** [comment]
I don't think we have those files. Maybe you can provide the folder so we can check them.

**Comment by millsdmb** [comment]
I will remove all the PUP, restart my pc and scan again, then refresh the
GIT. Then scan again​

**Comment by tilthz** [comment]
Closing this since the AV thing seems completely unrelated with the dark wallet.
