### ISSUE TITLE
Fonts on DW 0.5.0

### ISSUE THREAD

**Issue by JPCrypto** [darkwallet/darkwallet#153]
I'm running DW 0.5.0. The fonts look a little wonky. Any character that has a horizontal element is missing the horizontal piece. For instance the letter "H" looks like "I I"

**Comment by leafcutterant** [comment]
I have this too. Looks "darkly" cool with some letters, with others, it's unreadable.

On Win 7, Chromium portable

![456u](https://cloud.githubusercontent.com/assets/7106231/3402015/f763c97e-fd56-11e3-9193-0eec6e7e9409.png)

**Comment by tilthz** [comment]
@JPCrypto , are you also on windows?

can you guys tell me if you have cleartype enabled?

**Comment by leafcutterant** [comment]
I do have ClearType turned on (I think it's a default setting on Win 7), but turning off didn't improve the situation (the font even got messier by changing the settings, a browser restart brought it back to the "normal" unreadable mode).

**Comment by leafcutterant** [comment]
FWIW, Chrome font display on Windows has always been an issue for me, before switching to Chromium, Chrome portable had weird looking fonts too (and weird character substitutions), although nothing on the scale of this.

**Comment by JPCrypto** [comment]
@tilthz  Yes I'm on Windows 7

**Comment by tilthz** [comment]
chrome font rendering in windows is crappy by definition because it uses GDI instead of win's native directwrite API. Firefox doesn't have this problem in windows AFAIK.

I'm gonna look for a solution or fallback. Will update this when it gets done.

**Comment by tilthz** [comment]
Chrome 35 implemented DirectWrite rendering. It seems like it's not on by default yet and you have to enable it in chrome://flags/ - I haven't had the time to test, but this should fix the issue.

https://i.imgur.com/50e8oPX.png

**Comment by leafcutterant** [comment]
Nice, works as expected. Thank you @tilthz!

**Comment by thiswillbeyourusername** [comment]
I have this problem too (win-chromium v36)

``` CSS
-webkit-text-stroke: .3px;
```

Fixes it without enabling DirectWrite rendering. Not a good solution mind you, also the font looks slightly bolder with this method. Couldn't there be a JS detection so it uses arial if it's Win-Chrome? (or even revert back to using arial, what's wrong with arial? :tongue: )

**Comment by tilthz** [comment]
I guess the detection could be done, but the real question is how long it's gonna take for chrome devs to enable directwrite by default as it is definitely better. Have you played with -webkit-font-smoothing and text-rendering? These improve things in Linux and Mac, but I haven't had the chance to test it in windows yet.

**Comment by thiswillbeyourusername** [comment]
I haven't noticed any difference with -webkit-font-smoothing or text-rendering. According to stackoverflow other people can't get it to work on windows too, it's only for mac/linux at the moment.

According to http://stackoverflow.com/questions/11487427/is-there-any-font-smoothing-in-google-chrome/19582105#19582105 using the SVG version of the font fixes the bug - give me a second, I'm trying this out.

Update: SVG has improved the rendering but the font is thin and hard to read. Also, the Dark Wallet text/logo has jumped to a new line. SVG: https://i.imgur.com/VYr4X4V.png (using https://github.com/PerchCMS/perchdemo-swift/blob/master/public_html/fonts/Roboto-Light-webfont.svg) - no SVG: https://i.imgur.com/uF2zhSa.png (look at the euro symbol)

By the way, I love the new dropdown list for each transaction in the history! :+1:

**Comment by leafcutterant** [comment]
@tilthz Sorry for being a Chromium-noob, but where/how does one enable the options you mentioned? Not that my font rendering is bad, but after examining it closely, it could still be improved compared to my Firefox experience.

By the way the Chromium updates come out rapidly on the Dev channel and I read somewhere that they are looking to fix font issues in July. Today marks the start of July, so we might see changes anytime soon.

**Comment by thiswillbeyourusername** [comment]
@leafcutterant if you mean the -webkit-font-smoothing & text-rendering, that's CSS (you have to edit the \css\app.css of the extension).

**Comment by leafcutterant** [comment]
@thiswillbeyourusername Thanks, I referred to those. I'm dumb for CSS but I think I succeeded in inserting -webkit-font-smoothing, and it had no effect on font display. From what I read, this is a feature that was disabled by Chrome devs back in 2012.
I looked into text-rendering examples but had no idea how to add them to my CSS file.

**Comment by sembrestels** [comment]
Chrome 37 is out and it has DirectWrite by default. Maybe we can close this issue.
