### ISSUE TITLE
Update bitcoinjs-lib to 1.2.0

### ISSUE THREAD

**Issue by kyledrake** [darkwallet/darkwallet#155]
Announcement: http://pastebin.com/raw.php?i=ZDGdnB3z

**Comment by caedesvvv** [comment]
is there a document about api changes?

**Comment by kyledrake** [comment]
I believe you are using a version above 0.2.0, so it shouldn't be too different, but we did make quite a few interface changes even since then. Now that the refactor is done, we will be able to document the interface more, and make documents describing interface changes.

Note that you can now choose to include the package from npmjs.org if you wish, rather than vendoring it.

I'm \ccing @dcousens here, who can also help if you run into any issues. I might be able to do the conversion and send a PR. Your tests are pretty good and should catch most/all of the changes.

**Comment by caedesvvv** [comment]
Ok, yes I think we run pretty much under 0.2.0 but I see a lot of api changes came after. Anyways shouldn't be too hard to adapt will try soon and report if I see any blockers.

**Comment by caedesvvv** [comment]
Started to see what changes are needed and I see the api changes are pretty extensive, a few:
- massive cuts in convert module
- changes in ECKey  (priv -> d, getPub() -> pub) deleted methods (toBytes, fromBytes, add), (new ECKey() -> ECKey.makeRandom)
- changes in ECPubKey  (pub -> Q)
- HDWallet -> HDNode
- HDWallet.priv -> HDNode.privKey
- arrays -> buffers everywhere
- CryptoJS, BigInteger, Buffer not exposed so bit tricky to use out of the box?
- Bitcoin.network -> Bitcoin.networks (and all constants below changes too)
- new Transaction(data) -> Transaction.fromHex(data)
- Script.extractPubKeys -> gone?
- Bitcoin.Opcode.map -> Bitcoin.opcodes
- Transaction.ins -> no more outpoint, hash is not UIntArray (not str)... generally TransactionIn and TransactionOut gone

will keep editing this for documentation

**Comment by caedesvvv** [comment]
almost done with the migration to 1.1.4 at https://github.com/darkwallet/darkwallet/tree/new_bitcoinjs, needs some more testing to make sure everything is all right.

**Comment by dcousens** [comment]
Looks good, let me know if you want to do a google hangouts call / IRC
session or something and we can review the entire thing with you piping any
explanations if I find something a bit strange.

My first thought was why was https://github.com/darkwallet/darkwallet/blob/26e98c8666bf247aea77e5c4e9dd42fa262b77ab/vendors/wrappers/bitcoinjs.js#L43-L50 necessary?

Why not just use the WIF format? 

Doing so would make the code easier to review, require fewer changes and has practically a negligible performance cost given how often this code should run.

**Comment by dcousens** [comment]
Quick review of some of your changes.

https://github.com/darkwallet/darkwallet/blob/new_bitcoinjs/js/dwutil/multisig.js#L111
- Won't work
  ref:
  https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/transaction.js#L12

https://github.com/darkwallet/darkwallet/blob/new_bitcoinjs/js/model/tx.js#L65
- use `TransactionBuilder`, safer and relatively future proof in terms of our API.

**Comment by caedesvvv** [comment]
more notes on the changes I had to make:
http://sindominio.net/~caedes/migration.txt

also the following commit has most changes affecting the wallet:
https://github.com/darkwallet/darkwallet/commit/9516b170a246e0880414f50d39e43e4d70d5c530

I have modified bitcoinjs-lib only to expose some internal modules (index.js). I have added a wrapper that backports some old methods, also had to compromise the usage of the new api to keep backwards compatibility with the rest of the wallet code.

Like the change you point out. I undestand I wouldn't need those methods and in some cases I can adapt the wallet internally, but for now they are required to interface with other parts of the code.

**Comment by dcousens** [comment]
`bs58check`  is now a standalone package: require('bs58check')

edit: You just made me realize that is actually an API breaking change in the `1.1.y`
versions of the package... meaning we broke semver.  Damn.

I'll put out `1.1.6` fixing that...

edit: Fixed.  So Bitcoin.base58check will work for now, but it will be removed in
2.0.0, so, maybe keep that in mind.

**Comment by caedesvvv** [comment]
note I expose some internal bitcoinjs-lib dependencies, like base58check, because then I can use them without needing to require another copy (we also expose Bitcoin.BigInteger for example).

**Comment by dcousens** [comment]
Also, fromInputScript doesn't exist because it is not safe to use
consistently,  classifyInput itself is a "best guess"

**Comment by caedesvvv** [comment]
Ok will keep it in mind related fromInputScript and look for a better solution

**Comment by dcousens** [comment]
Other than that, your notes look solid.

**Comment by caedesvvv** [comment]
great :), I tried to take note of every change I had to make

also have some ideas about how to remove the different wrappers for backwards compatibility, but for now main priority was to make it work with minimal changes to the rest of the code.
next is maybe also adapting the rest of the wallet to the new bitcoinjs way, but need to think a bit more about it (like using buffers more through the app, cache privkeys in wif format...).

**Comment by dcousens** [comment]
To save on adding all that compression code,  why not just  use `toWIF/fromWIF` now, but bs58check.decode/encode it when interacting with the API.
That way it is only your model that is out of date.  This will protect you from possibly making a mistake which is one of the leading causes for problems (missing zero padding on the private key).

**Comment by caedesvvv** [comment]
will check the toWIF/fromWIF, was thinking to upgrade the model so I can just use it everywhere too, but needs a bit more thought

**Comment by caedesvvv** [comment]
btw, something I didn't write in the notes, I get broken unit tests in older firefox due to the usage of rng in ECKey.makeRandom (we use a newer firefox and it's all right but the buildbot dies on that one)

**Comment by dcousens** [comment]
That would be a crypto-browserify bug? Can you post the errors/broken tests so I can verify and submit a fix?

edit: Oh, `older` firefox... chances are it doens't have the crypto API? At which point, that means it is going to be unsafe; hence, unsupported.

**Comment by caedesvvv** [comment]
it's definitely unsupported by us just it's breaking the build bot... anyways maybe I can try hooking a mockup for browser crypto random on the test

**Comment by caedesvvv** [comment]
updated the branch to 1.2.0

**Comment by caedesvvv** [comment]
done
