### ISSUE TITLE
Documentation of the implementation of BIP39 >>BIP32

### ISSUE THREAD

**Issue by dabura667** [darkwallet/darkwallet#161]
I am trying to convince all projects I am contributing to place simple information on their READMEs to assist users in restoring their funds.

My suggestion is the following:
1. Read / contribute your feedback to the BIP0044 write-up, and keep it in mind for future projects.
   https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki
2. Place BIP32 HD path information as well as any non-standard usage of other BIPs (39 especially) in the README under "Independent Wallet Restoration" or some other name to denote the methodology for restoring the wallet.

Seeing as the wallet is already out in the open, switching to BIP44 is not prudent, but definitely I think that all HD wallets should publish restoration info in their READMEs.

Please let me know what you think of this proposal.

Thank you.

**Comment by leafcutterant** [comment]
This seems to be a good idea.

**Comment by dabura667** [comment]
https://wiki.unsystem.net/en/index.php/DarkWallet/HDWallet

I think this link should be included in the README.md on the main repository under the header "HDWallet restoration info" or something

**Comment by caedesvvv** [comment]
Note the info on HDWallet is a proposal, together with documentation about how it works now.

We are looking for feedback about implementing a final structure, but it's pretty sure the current one won't be the final, so we will have to do one migration.
