### ISSUE TITLE
"Pocket address" is shown after creating new pocket, but not shown after restarting

### ISSUE THREAD

**Issue by veox** [darkwallet/darkwallet#164]
As outlined in https://github.com/darkwallet/darkwallet/issues/163#issuecomment-49086983, this is an issue for the following reasons:
- the pocket address is no longer shown after restarting Chromium (and perhaps other cases);
- the pocket address is not scanned, so if anything is sent to it, it is not shown as received.

Since pocket keys/addresses are only an internal detail of the [wallet hierarchy](https://wiki.unsystem.net/en/index.php/DarkWallet/HDWallet#Tree_structure), I suggest the solution be not displaying "pocket addresses" at all, to minimise confusion.

**Comment by Regulus343** [comment]
I had the same issue after sending a small about to my spending "pocket" address. Is there any way to recover the BTC I sent to it? The address no longer shows up for me.

**Comment by dabura667** [comment]
Read #163 

There was a commit to temporarily spit out the private key of that address only. The commit didn't get merged, but if you merge it to your local, and run it. You could import that private key into another wallet and retrieve the bitcoins.

However, I would suggest not using Darkwallet for real bitcoins. If you would like some testnet coins to play around with, faucets will usually give you 2-4 BTC and it usually only takes less than 24 hours to process.

**Comment by veox** [comment]
The [commit in question](https://github.com/veox/darkwallet/commit/71b2da0c0d30200b3069b041f39f8d1b615754bb) is in my repo and shouldn't be merged - it's just a one-line hack to get a private key associated with a public key (in the form of an address).

To get its functionality, do (in your `darwallet` repo):

``` sh
git remote add veox "https://github.com/veox/darkwallet"
git pull -v veox hack-get-private-key-of-address
git checkout veox/hack-get-private-key-of-address
```

Then use that version to extract your private keys.

OT: As for testnet coin, you can get a little amount instantly from [helloblock.io](helloblock.io) with

``` sh
curl -X POST https://testnet.helloblock.io/v1/faucet/withdrawal \
    -d "value=100000000" -d "toAddress=<ADDRESS_HERE>"
```

**Comment by veox** [comment]
[Here's](https://forum.unsystem.net/t/bought-bitcoins-but-they-didnt-arrive-in-my-darkwallet-btc-company-provided-proof-that-the-btc-were-sent-what-do-i-do/287/13?u=veox) a more detailed explanation on how to use the workaround.

**Comment by caedesvvv** [comment]
Issue fixed so the pocket address won't show (was never intended to do so, but did appear because of refactoring error).

The funds won't be accessible for people that sent there, but will add some tool in alpha6 so this can be redeemed (besides exporting privkeys that is also in the pipeline). Sorry for the inconvenience to those affected but the funds are not lost even though they won't appear in the wallet for now.

**Comment by caedesvvv** [comment]
Also added the issue in the wiki since it's major, so we can track it for next alpha:

https://wiki.unsystem.net/en/index.php/DarkWallet/Alpha5/KnownIssues#Creating_pocket_shows_a_.22pocket_address.22_that_won.27t_show_afterwards
