### ISSUE TITLE
Sending from "Any" address fails

### ISSUE THREAD

**Issue by amingilani** [darkwallet/darkwallet#171]
You have to manually select which pocket you're sending funds from. the "Any" option says that you have no coins.

**Comment by caedesvvv** [comment]
duplicate of #116

**Comment by amingilani** [comment]
Has this issue been fixed? The last one and this one are both missing merge references!

**Comment by caedesvvv** [comment]
no it's not fixed yet, but this is a duplicate of #116 which is open, you can follow the issue there. thanks!
