### ISSUE TITLE
"Pocket" address issues

### ISSUE THREAD

**Issue by Attempt12** [darkwallet/darkwallet#175]
Hello,

I just sent some BTC to an unused address in a pocket that I created in Darkwallet, and it has a few confirmations, but the wallet never indicated that it had received any bitcoin. It is definitely arriving, but my balance does not reflect this. 

When I sent it, I never got a message immediately that it arrived, as I normally do. How to get the wallet to see these coins?

**Comment by amingilani** [comment]
Have you tried turning it off and back on again? :smile: 

Only half joking. Try doing that, if it doesn't work, try resetting DW (make sure you back up). I'm quite certain that would show you your balance.

**Comment by dabura667** [comment]
#164 ?

**Comment by gagecolton** [comment]
So it looks like the obelisk server was down and I was unable to access my coins. I'm finding that the obelisk server is the bitcoin note that the gateway server connects to. It would be nice if there was more documentation on how to setup the gateway server. I was not able to get my build of the gateway server up and running while the system was down. I'm just glad it is back up. I became less and less concerned about my coin being lost as I learned about how the infrastucture works. Once I realized that the bitcoin node was down (obelisk), then it all made sense. We need more documentation.

**Comment by dabura667** [comment]
@gagecolton 

https://github.com/bip32JP/bip32JP.github.io/archive/darkwallet.zip

Here, I made it in English, it will accept your 12 word seed (it will not accept the hex seed) and you can restore you addresses according to the following tree: I checked it with my own seed, and it works perfectly. Just download, unzip, and open index.html.

https://wiki.unsystem.net/en/index.php/DarkWallet/HDWallet#Alpha_Spec

Pocket structure
`m/0'/0 -> pocket 0 public`
`m/0'/1 -> pocket 0 change`
`m/0'/n*2 -> pocket n public`
`m/0'/n*2+1 -> pocket n change`

So the first keys of your first pocket ("Spending" by default I think)
`m/0'/0/k`
Change addresses for this pocket will be on
`m/0'/1/k`

Pocket 2 (aka "savings" I believe)
`m/0'/2/k`
Pocket 2's change addresses
`m/0'/3/k`

and so on and so forth. the even numbers (including 0) are the receiving addresses, and the odd ones directly after them are the change addresses.

Use this and see if you can recover your funds by changing `k` from 0 all the way up to wherever you think they may be. (each pocket's "k" keys start at 0 and increase by 1 every time they are generated. so unless you're using a ton. They will be in the lower numbers.

Ignore what was in my previous post.

**Comment by maddadder** [comment]
I really like this. I have a question though. In http://bip32.org/, is basically the sam implementation as this but it is different. So far it looks like the Chain Code is different, but that may not be the only thing. Why can't I use http://bip32.org/ for this?

**Comment by dabura667** [comment]
@charlierlee Because bip32.org just hashes any password (similar to a brainwallet) to generate the seed for the BIP32 chain, but DarkWallet uses Electrum's mnemonic method to mask a pre-generated seed.

It was literally about 5 lines of code to change from bip32.org to this... but bip32.org won't ever support this because the ONLY wallet that uses this type of combination is DarkWallet.

**Comment by amingilani** [comment]
@dabura667 This is wonderful work, you should really consider abstracting language, and making it multilingual. There are a lot of people on the Trollbox everyday complaining about similar problems.

**Comment by dabura667** [comment]
It's a tool using Electrum's mnemonic, and based off a tool I made for BIP39 + BIP32 usage with a Japanese alt.

https://bip32jp.github.io/
(Japanese wordlist and English wordlist for BIP39 and generates BIP32 wallet. Can be used to regenerate keys for Hive-web, breadwallet, etc.)

which is in turn based off of this site.

https://bip32.org/
(This site just hashes your passphrase like a brainwallet on steroids.)

**Comment by caedesvvv** [comment]
Ok, latest git and upcoming 0.6 release doesn't show the pocket address by itself, and also can scan for this with a new option in the seed scanner: "scan pocket master".

Also now the tool by veox to export private keys is available from tools.

So if you have any fixes, update to git/0.6 and run the seed scanner from tools.
