### ISSUE TITLE
Transactions received with the wallet open show no timestamp

### ISSUE THREAD

**Issue by tilthz** [darkwallet/darkwallet#183]
![screen](https://cloud.githubusercontent.com/assets/3986071/4704850/9b702746-5875-11e4-8d5e-0f2e83031f93.png)

This is how receiving a transaction while the main window is open looks like. It gets a proper timestamp the next time timestamps are refreshed.

Proposed solutions:

a) Show a string like "Just now" until the next time timestamps are updated (apparently each few minutes)
b) Show "Just now" until the transaction is 1 minute old, then switch to the timestamp

c) Show a live-updated timestamp with the seconds shown properly

**Comment by tilthz** [comment]
![scr2](https://cloud.githubusercontent.com/assets/3986071/4705585/31d47b72-587d-11e4-9da3-d71ea4fe0302.png)

**Comment by caedesvvv** [comment]
seems the timestamp filter is buggy
