### ISSUE TITLE
User shouldn't be able to get past wallet creation screen until completed

### ISSUE THREAD

**Issue by leafcutterant** [darkwallet/darkwallet#187]
When creating the first wallet, one can click on the top menu items and arrive to a non-functional, string-missing version of DW. Screen is from Settings but it's the same all over the UI. I suggest making the wallet fool-proof by blocking the user from doing anything other than creating a wallet as long as there is no wallet.

![clipboard01](https://cloud.githubusercontent.com/assets/7106231/4761649/06fb8fc4-5afa-11e4-9b60-861ebb1efc70.png)

Win7 x64, latest Chromium portable, latest dev release.

**Comment by caedesvvv** [comment]
Fixed by https://github.com/darkwallet/darkwallet/commit/bc00c9df28b8de6799228d34fec19882c6af70cb

**Comment by leafcutterant** [comment]
I's partly reopen this: now you can't get to string-missing sections while creating the first wallet, but you can still interrupt it and arrive to a totally blank black screen and you can return to create a wallet only by closing this tab and starting all over.

I suggest making the top left corner logo unclickable for the duration of the first wallet creation. (Though it should stay, so the unaware user can know where is s/he now, what app s/he's using,)
