### ISSUE TITLE
Trollbox not working?

### ISSUE THREAD

**Issue by millsdmb** [darkwallet/darkwallet#189]
I have tried on multiple computers (one win 8 one chromebook) using the latest release. Whenever I type anything in Trollbox/Trollnet or any channel, nothing happens. Am I missing something obvious?

**Comment by caedesvvv** [comment]
maybe you are not getting the interface updated, do you see what you write on the window?

**Comment by millsdmb** [comment]
No, nothing can be seen but other chatting. Chromebook is ver 38 beta iirc.

**Comment by tilthz** [comment]
I'm having the same issue

**Comment by millsdmb** [comment]
more info, when chatting directly between users it seems to work.

**Comment by caedesvvv** [comment]
can you check:
1) latest darkwallet git version, see if you have the same problem
2) Some plugin or chrome feature that could be conflicting

**Comment by Dark2014** [comment]
Same issue here!
Cant see what I have written. Cant see what others write in the channels.

1) Latest Darkwallet version, fresh installation (tried on Win7 and Debian).
2) Fresh Chrome without any changes or plugins.

But my hole internet traffic is forced to the Tor network, could this be the problem?

**Comment by caedesvvv** [comment]
can you try the git version?

**Comment by Dark2014** [comment]
I use the version from: https://github.com/darkwallet/darkwallet/releases/tag/0.6.0

Is this the right one?
(If not, please link the other version)!

**Comment by sembrestels** [comment]
Use this link: https://github.com/darkwallet/darkwallet/archive/develop.zip

This is the link you can find in the botom of the right sidebar in the repo's main page. It contains the unreleased latest work.
