### ISSUE TITLE
improving the "send to stealth address" experience

### ISSUE THREAD

**Issue by shea256** [darkwallet/darkwallet#193]
Hi there, I have a few questions about stealth addresses and stealth address usage with DarkWallet, as well as some suggestions about how the experience could be improved.
1. With DarkWallet, does each pocket just have one stealth address?
2. Is there a way to make DarkWallet the default handler for Bitcoin URLs?
3. If the answer to question #2 is yes, then there a way to make "bitcoin:<stealth_address>" URLs autocomplete the address field in the send tab?

I ask because right now on Onename we only support standard Bitcoin addresses but we'd like to support stealth addresses for privacy reasons, as well as raise awareness about stealth addresses and encourage other wallets to support payment to stealth addresses. One very helpful thing would be to be able to point to a great user experience with stealth addresses on DarkWallet.

**Comment by sembrestels** [comment]
Hello,

Yes, there is just one stealth address per pocket, each one with two different public keys (one for scan and one for retrieve the funds).

Darkwallet should be the default handler for bitcoin URIs, if it is not in your case, can you write here your chrome version and darkwallet version, please? Can you also check if an error appears in the console (press F12 to see).

To the last question, Darkwallet already should fill the fields with a bitcoin URI with the amount and/or the label.

If you want to implement the stealth addresses, please look at our stealth library repo: https://github.com/darkwallet/stealth.js

**Comment by shea256** [comment]
OK cool. Is there a way we can see/download the scan private key and spend private key for each pocket?

And I re-installed the extension and it is now the default bitcoin URI handler.
(for reference: Chrome Version 40.0.2201.2 canary (64-bit), DarkWallet Version 0.50)

I do know that wallets will try to overwrite each other to be the default handler. Coinbase has a button where you can re-issue it as the default handler. DarkWallet should definitely have a button for that as well, or else its going to be overridden for most users.

**Comment by ABISprotocol** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

This is good to see happening, thank you @rxl ~ [background on this
here](https://github.com/darkwallet/darkwallet/issues/154#issuecomment-48421580).

Side note:  When you have some time, check out also
[BitName](https://github.com/abisprotocol/bitname) and
[IDMAS](https://github.com/cjbauer/IDMAS).
- \- Cheers

Ryan Shea wrote:

> OK cool. Is there a way we can see/download the scan private key 
> and spend private key for each pocket?
> 
> OK I re-installed the extension and it is now the default bitcoin 
> URI handler. (for reference: Chrome Version 40.0.2201.2 canary 
> (64-bit), DarkWallet Version 0.50)
> 
> I do know that wallets will try to overwrite each other to be the 
> default handler. Coinbase has a button where you can re-issue it
> as the default handler. DarkWallet should definitely have a button
> for that as well, or else its going to be overridden for most
> users.
> 
> --- Reply to this email directly or view it on GitHub: 
> https://github.com/darkwallet/darkwallet/issues/193#issuecomment-61508865
> 
> ---
> 
> http://abis.io ~
> "a protocol concept to enable decentralization
> and expansion of a giving economy, and a new social good"
> https://keybase.io/odinn
> -----BEGIN PGP SIGNATURE-----

iQEcBAEBCgAGBQJUV9AoAAoJEGxwq/inSG8C+dwH/0+2qpds0SWWnb2ji1yAzmhx
z3DeVj8ywj6QiIf2dwGZJMHYfxwmNvKkiXlMrfaFCgrtiSeCDPKY6mKUw2wevAg+
hxge4uSEC/U6tY+nzfVRRMVMlTdSYPDvv2lRYOtXz5O7nHkJ76so4xGCVWxYYr3D
aLE1IwWrkc7A2VQ+eDDI2NWVGG7fz5GA03LdtUQsIO3xuIocxbrTD89vq5ywlLai
KG+pFCLeZRFZ8EnGN85kCeqrjQnSTjzHqdkhxPef3ZC9g6m65/BdM+a4ENnczmxl
GWrMsL3HU7HH+cJkuMHVtl0nEFUHBOKz8spVpZP44wWY24lKiU7dD0OSiEsq9VA=
=QqWB
-----END PGP SIGNATURE-----

**Comment by caedesvvv** [comment]
Seems this is sorted out. Please reopen otherwise.
