### ISSUE TITLE
Scan did not found my stealth transfer

### ISSUE THREAD

**Issue by Dark2014** [darkwallet/darkwallet#196]
I did a "restore from seed" with 3 wallets.
If I open the wallets my coins are gone, so I start the scan.
For 2 wallets all coins was found, but for the the last wallet one transfer is already missing.

I have the same wallet on another pc, so I can check what happens and I see that the missing transfer was a stealth one.

So maybe a bug? Or what can I try to fix this?

**Comment by caedesvvv** [comment]
You need to use tools->receive stealth instead to scan for stealth transactions.
