### ISSUE TITLE
Localization won't get many contributors if they have to run a command line.

### ISSUE THREAD

**Issue by dabura667** [darkwallet/darkwallet#198]
Can't you set up Transifex to use the web interface...?

Every project I've translated has taken me almost 0 time because Crowdin / Transifex have such easy and fast web UIs for translating.

I was wondering what the reasoning for not utilizing it was.

afaik Transifex and Crowdin both offer free use to open source projects... which explains why so many Bitcoin projects use them...

Dark Wallet is the FIRST one I've encountered that doesn't allow the web UI for the localization management service.

This will only get translated in languages by people who are both programmers / speak another language... whereas those aren't always necessarily the best translators. Except for me, I rock.

**Comment by sembrestels** [comment]
The web interface is here: https://www.transifex.com/projects/p/darkwallet/resource/darkwallet/

Is that what you were looking for?

**Comment by dabura667** [comment]
oops!

I just applied for Japanese. Thanks!

**Comment by sembrestels** [comment]
Japanese accepted. Thanks!

**Comment by dabura667** [comment]
Japanese finished and approved.

Let me know if you add / change any strings.

Also, how often are you merging the i18n from Transifex?
