### ISSUE TITLE
How good is CoinJoin in Darkwallet?

### ISSUE THREAD

**Issue by Dark2014** [darkwallet/darkwallet#199]
To make a BTC transfer untraceable there are 3 important things: Following, Amount and Time.
1. Following on Blockchain should be not possible.
2. Amount of input and output should be different and random.
3. Time between input and output should be long and random.

For example Bitcoin Fog:
1. Following on blockchain is not possible, because the coins are different.
2. Amount is splitted in random amounts and a 1-3% random number of coins will be taken.
3. Time between input and output can set to hours/days and is also random.

So what about CoinJoin?
1. Following on blockchain is nearly impossible for humans, but what about a hardware attack?
2. Amount is splitted and send with others, but input/output match, so its possible to recalculate transfers!
3. Time is 0, so it is impossible to hide between others in the blockchain.

CoinJoin vs. CoinMix by Bitcoin Fog:
http://css.csail.mit.edu/6.858/2013/projects/jeffchan-exue-tanyaliu.pdf

Kristov Atlas about CoinJoin problems:
http://www.coindesk.com/blockchains-sharedcoin-users-can-identified-says-security-expert/

Software to trace and identify CoinJoin-User:
http://www.coinjoinsudoku.com/advisory/

So what about this problems in darkwallet?
And how good is Darkwallet-CoinJoin compared to Blockchain-CoinJoin?

I think a Join is always a closed process, so Following on blockchain is always possible.
Also a random Time delay will be difficult to build in darkwallet and the benefit is also very low I think. For a pool (mix pool) of BTC is a random delay a extremly strong feature, but for a Join?.

So what about the Amount? Darkwallet could splits the coins in equal parts and mix with different users in CoinJoins. So the CoinJoin is still traceable but in this case it is not possible to recalculate because of equal amounts, so the tracer will end up with hundreds of addresses with equal amounts.

So something like this:
http://blog.oleganza.com/post/67885463476/how-to-launder-bitcoins-perfectly

@ Mods
If this is the wrong place, fell free to move it to the right place and close here.

**Comment by caedesvvv** [comment]
0.7 Darkwallet's coinjoin produces two outputs of equal amount that you can't uniquely link to either of the inputs.
