### ISSUE TITLE
Crypto Goals

### ISSUE THREAD

**Issue by weems** [darkwallet/darkwallet#20]
## Security

How is the backend security coded? I think the strongest 2048 or > should be sought so that those who try to make Bitcoin more palatable to authorities will fail.

**Comment by tilthz** [comment]
We would never use less than 4096 rsa or 256 bit ec

**Comment by weems** [comment]
Thanks.

**Comment by ABISprotocol** [comment]
Please add a note on how this may be able to be interact with Zerocoin implementation at such time when Zerocoin / zerocash is further developed, in light of this March 7 2014 item. 
http://ifca.ai/fc14/bitcoin/papers/bitcoin14_submission_12.pdf  Please comment on Section 3 in particular (the 'Everlasting Anonymity' section) as well as the reference to a large modulus (example is given of 3072 under section 4.2, 'Zerocoin Attack Surface,' Forgery subsection) as it might relate to aspects of the darkwallet development.

**Comment by weems** [comment]
or the following bug with openssl and TLS https://www.openssl.org/news/secadv_20140407.txt
