### ISSUE TITLE
Built in testnet faucet

### ISSUE THREAD

**Issue by hizzvizz** [darkwallet/darkwallet#204]
I tried walking through using the Darkwallet with two other users and we were all unable to transmit Bitcoin using the testnet. 

There should be a testnet faucet built into the GUI so people can try the wallet without using their own Bitcoin or having to search the web for testnet faucets.

**Comment by dabura667** [comment]
https://web.hivewallet.com/?network=testnet

This wallet allows you to use testnet from a smartphone web browser. You could load up some testnet coins into it and then have him copy + paste his address into a chat app or something so you can send it to him.

Testnet is not for creating a "smooth user experience" as it is made for devs.
If you would like to show off the testnet wallet to a friend, you should obtain testnet coins and send him some.

Won't Fix +1

**Comment by genjix** [comment]
It might be a cool way to introduce newbies to a Bitcoin wallet though without using real coins :)

**Comment by caedesvvv** [comment]
We can do this but would be cool if someone checks out some faucet with an api or simple http mechanism that we can trigger from darkwallet. (we have thought about this before and it's a good idea)

**Comment by caedesvvv** [comment]
Btw, @genjix I think one problem is the txradar component in the testnet gateway is not working properly, I see:

 Error with TxRadar: Service stopped

when starting the testnet gateway

**Comment by caedesvvv** [comment]
noting this here from an email by veox:

curl -X POST https://testnet.helloblock.io/v1/faucet/withdrawal \
 -d "value=<satoshis>" \
 -d "toAddress=<address>"

we can integrate an api like this in darkwallet easily, feel free to paste here other similar commands we could use.
