### ISSUE TITLE
Website is borked/parked

### ISSUE THREAD

**Issue by topynate** [darkwallet/darkwallet#207]
https://darkwallet.is now has a security certificate from www.parkingcrew.com, and displaying a 'parked' landing page.

**Comment by ABISprotocol** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Strange,

It's back up now as far as I can see.
Was there ever an issue like that before (borked/parked) - note, I saw
it when it was in the borked/parked condition earlier, it seemed brief.

Wonder if had to do with the Spanish stuff (and one wonders if the
Icelandic stuff as well being that there has been some unenforced
nonsense in Iceland for a while)?

Is part of this a test (or maybe, a shot off the bow to see if they
can push the support infrastructure, so forth)?

topynate:

> https://darkwallet.is now has a security certificate from
> www.parkingcrew.com, and displaying a 'parked' landing page.
> 
> --- Reply to this email directly or view it on GitHub: 
> https://github.com/darkwallet/darkwallet/issues/207

---

http://abis.io ~
"a protocol concept to enable decentralization
and expansion of a giving economy, and a new social good"
https://keybase.io/odinn
-----BEGIN PGP SIGNATURE-----

iQEcBAEBCgAGBQJUm8uaAAoJEGxwq/inSG8CuVgH/3clGQWa5c+myaYlKogdPOy3
6AcV+FZVCBWJhZ0bAgPfV4GbBRPibePWw222azsGoZJgui6O1PEMC04RpdjNPKXL
rADA5rgOWYaMvvQHkMwVh47tOTyAz7aszXmtJ5/mgOAM0U2ablolU6NzFwyCy+i8
lzehi6kEulVx0O1ABS6AOas9VkBu96Ruj/CpfBQSBAoSnh/G/Jot/8lla51fOvgb
C64MquruZkS2LbwnriuGdU+U0vXiJz6H1IJx7Ot2cUuN5Gu1lXUz/ga9Db3+oCXk
RvN7IcF9N+NgJlrijwaagODgvud0KQnlvgffrsfFkUWgpbNU98N+dGidf1lLeQ8=
=5PF+
-----END PGP SIGNATURE-----

**Comment by caedesvvv** [comment]
sorry, this was the domain expiring :P
we updated it but due to burocratic error took a few days to come back (also coincidence with holidays..)
anyways, yes it's back up since a few days
