### ISSUE TITLE
PLEASE HELP. Error Importing private key. Unknown key format. Also 0 confirmations on all transactions

### ISSUE THREAD

**Issue by danj94** [darkwallet/darkwallet#210]
My BitCoin is stuck in my wallet. When ever i try to send a transaction it gets stuck at 0 confirmations and won't go any further. So it will not appear in my BlockChain wallet. 
I tried to get my BitCoin out by exporting the private key and then importing to block chain but block chain gives me this error everytime.. 
Error importing private key: Unknown Key Format 

Please help I am really quite worried here.

**Comment by danj94** [comment]
Also first person to help me get 0.3btc

**Comment by dabura667** [comment]
Hey there.

When you exported your private key, did you copy the part AFTER the comma? or did you just copy the whole thing (starting with 1)?

To import to other wallets you must only copy the part after the comma, it starts with a K or L.

Also, please import to blockchain.info using their PC web browser version. Currently Android and iPhone is not compatible with compressed private keys (starting with K or L)

**Comment by dabura667** [comment]
Also, when you send, try clicking "Advanced Settings" on the send screen and UNCHECK "CoinJoin mixing enabled"

Then your transaction should go through fine.

**Comment by millsdmb** [comment]
I see rebroadcasting may have been added but I don't see the option.
Running the latest git.

-sent via mobile device

**Comment by veox** [comment]
This conflates two issues.

`1.` "Unknown key format" when importing to blockchain.info.

Covered by @dabura667's comments. See above.

`2.` Zero confirmations on transactions.

The broadcaster component of the backend server was unstable. Therefore both are being redesigned, which involves bringing them down temporarily. This is expected to continue at least until Darkwallet is in beta.

For how to rebroadcast a transaction, see #211.

**Comment by caedesvvv** [comment]
Should now be possible to rebroadcast, clear the transaction or even clear history to let the wallet refetch it.
