### ISSUE TITLE
Pocket's name breaks into multiple lines in side panel if long and with spaces

### ISSUE THREAD

**Issue by leafcutterant** [darkwallet/darkwallet#220]
Came across this when testing the commit for #218. It happens only with "longname longname longname" type of names.

![clipboard01](https://cloud.githubusercontent.com/assets/7106231/5889489/5cdb672e-a42a-11e4-9363-d8e9b960b706.png)

**Comment by veox** [comment]
Simple fix provided. Not sure if it's a proper one in regards to style.

Perhaps @tilthz will process them all in one go once there are no more changes?..

**Comment by leafcutterant** [comment]
Tested; confirmed it to be working. Thanks, @veox! Can't say much about the coding style, if it's okay, I suggest pulling the commit.
