### ISSUE TITLE
Wiki manual lists testnet faucet available in 0.8, but it was added later

### ISSUE THREAD

**Issue by veox** [darkwallet/darkwallet#225]
29770f27e9c3a663c2803ce26ccbedb62db19cdc could become 0.8.1 (note there's 6c5f6a85168ebf8a8bd95a851306ac1b5fa2c4c3 between 0.8 and that, not related to faucet functionality).

Alternatively, we could edit the [wiki](https://wiki.unsystem.net/en/index.php/Darkwallet/Manual#Testnet_faucet), adding a note or something.

Or both.

**Comment by caedesvvv** [comment]
Where does it say it was available in 0.8?
Note the manual is for head, not necessarily for latest release (should be close enough).

**Comment by veox** [comment]
You are correct. I assumed the manual is for tagged versions.
