### ISSUE TITLE
Sign, verify and export tools broken

### ISSUE THREAD

**Issue by veox** [darkwallet/darkwallet#228]
They used to write into the middle of the _Tools_ window, but since the `tools` div has been moved to the _Development_ window, these tools no longer work.

Introduced by 63a7686f436cd6eec48ee8123eeacd70f3166657.

Two possible solutions:
- bring `tools` div back (it's only used by `signing.js` and `exporting.js` now AFAIK);
- rework for output (and possibly input) for these tools to show in a separate (modal?) window, with same _Copy to clipboard_ and _Close_ buttons.

**Comment by JasonThePM** [comment]
Agreed. I have funds stuck in a wallet now and no way to export the private key to move funds manually.

**Comment by leafcutterant** [comment]
@JasonThePM, any chance with downloading the 0.7 release (it's here in this repo), importing seed and exporting keys?

**Comment by JasonThePM** [comment]
Possibly. But Obelisk AND the broadcaster were up a few days ago and I just
sent my coins out. I'm going to wait a while before I use DarkWallet again.

**Comment by veox** [comment]
A workaround for exporting is available: https://github.com/darkwallet/darkwallet/pull/233

**Comment by veox** [comment]
Workaround rebased on current HEAD: #240.

**Comment by caedesvvv** [comment]
Fixed with d6466ac9c37f63224fb8b1dd0b22abbfb4bb3ebc
