### ISSUE TITLE
Pocket funds not showing up

### ISSUE THREAD

**Issue by TMMTMM** [darkwallet/darkwallet#241]
After signing up to Dark Wallet I transferred 3 amounts from Armory into DW's "spending" pocket, using the two addresses generically generated. The funds showed up almost immediately to both addresses.

I then transferred another two amounts from Armory into the generic "business" pocket using the two addresses in the business pocket.

In all cases I had renamed the addresses from their generic titles.

The funds sent to the business pocket are showing as cleared/confirmed on blockchain.info but are nowhere to be seen on DW.

Any suggestions on how to recover the funds?

**Comment by TMMTMM** [comment]
Update: DW does not seem to be connecting to the server. I've tried the coinkite server as well (obelisk.coinkite.com:9091), no luck.

**Comment by veox** [comment]
Sadly, there is only one server ATM, and when it goes down, DW has nowhere to get blockchain updates from. You'll have to wait until the server is up.

As to using coinkite's server - DW requires the server operator to run additional `gateway` software together with `obelisk`. I'm sure they're not doing that.

P.S. One can, however, run a `gateway`, and point it to an `obelisk` running on someone else's machine. This setup is not exactly secure.

**Comment by TMMTMM** [comment]
Doesn't look like it. Feedback much appreciated, will wait out.

Hopefully btc doesn't priceshift much lower in the meantime!

**Comment by caedesvvv** [comment]
This is attributed to backend problems so closing.
