### ISSUE TITLE
Sending to the stealth adress doesn't works

### ISSUE THREAD

**Issue by ghost** [darkwallet/darkwallet#242]
I have sent bitcoins from one of my wallet to another of my wallet. I typed the stealth adress of the second adress in the "send" tab of my first wallet, but it has been a week that it is write <strong>sending</strong>  in the first wallet and nothing appears on the second wallet. 
My questions are :
1) Why it hasn't worked ?
2) Is there a way to undo the sending (because currently I lost all my btc)
Thanks in advance !

**Comment by veox** [comment]
The server was probably down. You can clear/resend from the history tab.
