### ISSUE TITLE
Wallet plugins

### ISSUE THREAD

**Issue by necrose99** [darkwallet/darkwallet#243]
Bitcoin 
Armory 
Blockchain json wallet 
https://electrum.org/#home

what do all these have in common, no ability to inter operate or IE my cell or other wallets clients,
some wallet formats are more secure than others,  however if you re-install pc/linux some wallets IE armory or electrum can be a real SOB to restore.
also makes a thorn to migrate coins from multiple wallets , I as of yet have no bitcoins,  mainly due to .001 move the coins about or the backup/restore/migrate/Android-mobile editions, etc, 
- bitcoin /litecoin wallets should be very secure
- bitcoin /litecoin wallets should be also portable between clients. 

One wallet IO plugin stack to rule them all ? meh why not?

**Comment by caedesvvv** [comment]
There are a set of bip that aim to reach this interoperability, our aim is to support them as well.
Closing since this is already in our goals (supporting standards for interoperability).
