### ISSUE TITLE
Restoring from seed does not recover mixed funds

### ISSUE THREAD

**Issue by justusranvier** [darkwallet/darkwallet#244]
No matter what options are provided to the Seed Scanning option, it does not recover 100% of the funds in a wallet if the wallet had previously performed CoinJoin transactions (via background mixing).

At least one other user on the #darkwallet channel (veox) has encountered the same problem.

**Comment by veox** [comment]
Yes, I have.

Uninformed guess: perhaps the mixer and scanner are not using the same HD key structure.

**Comment by justusranvier** [comment]
I background mixing back on under the assumption that as the wallet performed more CoinJoin operations it would reuse the same addresses for mixing and discover the missing funds.

This appears to be the case - as my wallet finds more CoinJoin partners it starts scanning the appropriate addresses and my displayed balance is increasing back toward the correct value.

This address reuse degrades the quality of the mixes and means I have to wait for the network to generate more mixing events until I get access to all my money, but at least the funds aren't permanently lost.

This is a serious bug that should be fixed.

**Comment by ghost** [comment]
I've had the same happen to me. When the mixing addresses get used again I have to restart chrome for the balance to update with both the previous and the last mixing transaction.

**Comment by caedesvvv** [comment]
the addreses can be scanned with the "Breadth" parameter (2 being just public and change, beyond that are the mixing levels.

**Comment by veox** [comment]
It's been a long time, and I haven't logged the procedure to repeat this properly.

I think this was the bug where restoring from seed and performing a scan (even a very deep one) _did_ detect CJ transactions, but _did not mark_ them as CJ.

In addition, the balances looked wrong. Might have been an issue with balance-checking, too.

In essence, to verify this issue we'd need two copies of the same wallet: one pre-restoration and one post-restoration.
