### ISSUE TITLE
Possible issue with coinjoin/mixing?

### ISSUE THREAD

**Issue by That1guy55** [darkwallet/darkwallet#245]
I have 2 wallets. 1 and 2.  I have been playing around with Darkwallet trying to get a feel for it.

I have ticked off "mix funds on this pocket" and also enabled it on send.  I sent 1btc from wallet 1 to my stealth address on wallet 2. But how can I verify if coinjoin worked and coins were mixed?  Isn't it potentially bad-news if one thinks they are sending mixed coins, and then they end up sending unmixed?  

Is there no way to verify coinjoin is functioning?

**Comment by miragecash** [comment]
You'll have to verify it by using a blockchain monitor. I think that the documentation says that it will try to mix your coins for 60 sec but if no peers are found sending coins, then it will just send them out unmixed. I only see zero to 1 peers at any given time in the "Lobby" tab so expect your coins to be sent unmixed most of the time.
