### ISSUE TITLE
Gateway/Obelisk issues / incentivization

### ISSUE THREAD

**Issue by ghost** [darkwallet/darkwallet#252]
Seems like a lot of the gateways/servers are no longer available and I also get a bug with the 'add server' feature in settings on the latest Chrome (where it won't add the IP).

Would it be possible to improve discovery / addition of servers, also to incentivize them to encourage decentralization, e.g. with fees?

**Comment by hoffmabc** [comment]
OpenBazaar will be running testnet and mainnet libbitcoin servers. I believe Airbitz does too. We should start to figure out a better way to organize and pool these federated servers for the benefit of all.

**Comment by ghost** [comment]
Agree with that, if the server layer can be decentralized it really raises the peg for DarkWallet as this decentralized private-payments layer on top of Bitcoin, I think theres a lot more that could be done with that architecture and I don't think there's anything in the Bitcoin ecosystem like that.
