### ISSUE TITLE
How did Dark Wallet work?

### ISSUE THREAD

**Issue by nopara73** [darkwallet/darkwallet#264]
I am unable to find any specification/documentation/research paper/whitepaper that would let me figure out the exact way how Dark Wallet worked/what was the basic idea.  

Can someone help me out?

**Comment by gasull** [comment]
The old wiki:

https://web.archive.org/web/20160512221849/wiki.unsystem.net/en/index.php/Darkwallet/Manual

The old website:

https://web.archive.org/web/20161019082921/www.darkwallet.is/

**Comment by nopara73** [comment]
## Protocol as I Understand

If I understand it correctly, these are 2 party coinjoins and the protocol is this:

1. Receivers are constantly listening.
2. Sender announces a transaction with its pubkey.
3. Receivers are answering to the Sender's pubkey with encrypted message.
4. Transaction negotiation, etc...

I have two major issues with this. How are they (if at all) solved?

## My Issues

### 1. Spy Attack
Receivers can listen and see all the transactions those are published to the channel. This way, if a CJ transaction appears on the blockchain, the inputs and outputs can be trivially linked based on the announcement transaction.

### 2. DoS Attack
A malicious actor can set up many quick receivers without any cost, thus preventing most (if not all) of the mixes from happening.

## Archived Source

I also took a screen shot of the relevant section of the links, let's keep it here for completeness:

![image](https://user-images.githubusercontent.com/9156103/44709920-23b51680-aaab-11e8-9bef-d7ecd0e59858.png)

**Comment by narodnik** [comment]
1. We had a special service we called the broadcaster which is just a transaction broadcast proxy

2. No solution for that. Doesn't seem to be an actual problem in practice.

**Comment by nopara73** [comment]
Thank you!
