### ISSUE TITLE
Verifying seed on new wallet fails 

### ISSUE THREAD

**Issue by starkers** [darkwallet/darkwallet#35]
after pasting in the 12 word seed on a fresh wallet clicking "Finish" does not respond

http://i.imgur.com/U1IuyGV.jpg

http://i.imgur.com/wQFkueZ.jpg

**Comment by caedesvvv** [comment]
Fixed by:

https://github.com/darkwallet/darkwallet/commit/e222cffb8343fc56a3dbe676584dfb50a9d0f5d0

Thnx for reporting!!!!
