### ISSUE TITLE
Make the header DW icon clickable

### ISSUE THREAD

**Issue by leafcutterant** [darkwallet/darkwallet#41]
My instincts make me click on it, I think it'd be ergonomic if it redirected the user to Wallets -> All pockets. You could even merge it with the Wallet button.

![clipboard01](https://cloud.githubusercontent.com/assets/7106231/2851915/6dd338ae-d126-11e3-8cda-28641bac57f5.png)

**Comment by leafcutterant** [comment]
Thank you! One little addition: the cursor could change to the pointing finger as with other buttons, indicating that the element is clickable.

**Comment by sembrestels** [comment]
It is not another section, it just redirects to wallet, so I find confusing promote the two links.
