### ISSUE TITLE
Currency selection

### ISSUE THREAD

**Issue by leafcutterant** [darkwallet/darkwallet#42]
In Settings, I think the default currency should be US dollar, that's the most widely used way to value BTC. Or the wallet could detect the localization settings of the browser and adjust the local currency. Plus, on the list, United Arabe Emirates in the first because there is an accidental space as the first character.

**Comment by sembrestels** [comment]
United Arab Emirates is first because its symbol is AED, and goes first alphabetically.
About default fiat preference, we can try to derive it from the user-agent.
