### ISSUE TITLE
Shout box visibility

### ISSUE THREAD

**Issue by leafcutterant** [darkwallet/darkwallet#45]
The shout box and it's type area fades into the background on my LCD screen (unless I make my room totally dark). I suggest coloring it a little bit lighter.

**Comment by tilthz** [comment]
can you provide a screenshot, please?

**Comment by DobZombie** [comment]
The gamma setting yout Lcd may need callibrating.
I suggest that you google "gamma calibration utility"
And then go from there.
:)

I do agree that the text brightness could be turned up a touch.
For functionality over style (which is quite sexy btw)

**Comment by leafcutterant** [comment]
Thanks for the tip. I calibrated my gamma and it's still the same. When looking at the screenshots, consider that for LCD displays, the higher the position of screen area is, the lower the contrast becomes ( = it becomes more indistinguishable).

Text area unselected:
![a](https://cloud.githubusercontent.com/assets/7106231/2879274/d6b1a722-d467-11e3-8698-cb2eb7d567d1.png)

Text area selected:
![b](https://cloud.githubusercontent.com/assets/7106231/2879279/e4be2b74-d467-11e3-8c86-be60d836a71b.png)
