### ISSUE TITLE
Option to turn off animations

### ISSUE THREAD

**Issue by leafcutterant** [darkwallet/darkwallet#51]
Users with weak hardware resources and those who like quick responses would appreciate an option to turn off animations. What do you think?

**Comment by caedesvvv** [comment]
definitely +1

**Comment by leafcutterant** [comment]
Thank you for the quick response!

Now major animations can be turned off, but buttons and tooltips are still animated.
Also, tooltips behave weirdly; they appear in the top left corner and "fly" to the element.

**Comment by sembrestels** [comment]
Yes, we should fix the flying tooltips. @tilthz Do you know what can it be?
