### ISSUE TITLE
Selecting "All" pockets displays the stealth address of the top pocket...

### ISSUE THREAD

**Issue by leafcutterant** [darkwallet/darkwallet#53]
...while it shouldn't, because you can't receive to "All". This is confusing, some might think it is a separate pocket.

**Comment by caedesvvv** [comment]
at the moment it's intended as your main address, and yes it's the address of the main pocket.

maybe it's more a matter of presentation we will think about it.

**Comment by caedesvvv** [comment]
We removed the addresses in the"All" view to avoid confusion.

**Comment by leafcutterant** [comment]
Many thanks!
