### ISSUE TITLE
Funds not spendable

### ISSUE THREAD

**Issue by bobberb** [darkwallet/darkwallet#56]
In my "spending" pocket, two balances are listed (why?)

it reads:

spending 0.17477567 BTC (85.83 $) 1 BTC (491.07 $)

Both balances are confirmed on the blockchain (https://blockchain.info/address/16YgBcVHxnEMX2EhfTjniKdrsR6xbZYp28) , however I cannot initiate a transaction over 0.17477567 BTC.

**Comment by caedesvvv** [comment]
in that case, the one on the left is confirmed, the part on the right is unconfirmed.

what does it say that you can't initiate?

**Comment by caedesvvv** [comment]
closing this tasks since we have no feedback and fixed many issues related to this also made balances more intuitive.
