### ISSUE TITLE
Change address funds not included in wallet balance

### ISSUE THREAD

**Issue by kristovatlas** [darkwallet/darkwallet#59]
On the testnet: Sent 1 BTC to my own stealth address with 4.9999 BTC change. Wallet shows that the change address received the change, but does not include this in the wallet's total balance. Final balance should be 5.9999 BTC but is 1 BTC nstead.
![screenshot from 2014-05-02 03 30 29](https://cloud.githubusercontent.com/assets/7227529/2860446/ee089d98-d1cb-11e3-8903-7e8b171d65ef.png)

**Comment by caedesvvv** [comment]
Its a gui updating issue and after changing pocket and back should show up properly.

Will close the task when we review this area.

**Comment by caedesvvv** [comment]
should be fixed now.
