### ISSUE TITLE
Testnet CoinJoin transactions hang at 33% and never complete

### ISSUE THREAD

**Issue by kristovatlas** [darkwallet/darkwallet#60]
Screen shot taken many hours after initiating stealth address send. 
1 pending CJ tx in wallet #1:
![screenshot from 2014-05-02 03 35 19](https://cloud.githubusercontent.com/assets/7227529/2860463/61a73020-d1cc-11e3-85dc-b0adf92c959d.png)

2 pending CJ txs in wallet #2:
![screenshot from 2014-05-02 03 36 48](https://cloud.githubusercontent.com/assets/7227529/2860470/8ee4ea82-d1cc-11e3-846b-9ce9ca6ae527.png)

**Comment by caedesvvv** [comment]
Should be taken care of by https://github.com/darkwallet/darkwallet/commit/9f0002fc9335723098c169d32534b55b05fd6757.

**Comment by millsdmb** [comment]
still happening for me (MainNet),

![image](https://cloud.githubusercontent.com/assets/7471116/2871898/82abec76-d32e-11e3-8fd9-7427f55becfe.png)

**Comment by kristovatlas** [comment]
Same here, testnet, for MD5(darkwallet-develop.zip)= 2c76c4626bd24fbf3c2f46b547398ae2

**Comment by caedesvvv** [comment]
Testnet mixing was fixed right before alpha4.
