### ISSUE TITLE
"Settings" button font (in the header) is not the main font

### ISSUE THREAD

**Issue by leafcutterant** [darkwallet/darkwallet#61]
(It appears only when Developer mode is turned off.)

**Comment by tilthz** [comment]
Can you provide a screenshot? which os?

**Comment by leafcutterant** [comment]
Win 7 x64, latest Chromium portable.

![clipboard01](https://cloud.githubusercontent.com/assets/7106231/2864065/18dfca9c-d20c-11e3-8b7d-3658f1a71611.png)

**Comment by tilthz** [comment]
Is this issue still happening? has anyone else reproduced it?

**Comment by leafcutterant** [comment]
For me it persists.

**Comment by tilthz** [comment]
Can you try after 2cf8b8d4410826bcfb6179d0ca242f5c3779ff1a?

**Comment by leafcutterant** [comment]
Okay, this solved it! Thanks.
