### ISSUE TITLE
Can access the wallet before creating an identity

### ISSUE THREAD

**Issue by c055** [darkwallet/darkwallet#64]
Hi Dudes,

first of all thx for effort and for launch first alpha version! When i try to create a new pocket, i can't save it. Nothing happens when clicking the ok button for creating a new pocket! Test on VB - win7 and chrome ... hope it helps...

![dark_issue_click](https://cloud.githubusercontent.com/assets/6280810/2861925/fc613edc-d1e8-11e3-96ab-d6f2510df0a3.jpg)

**Comment by c055** [comment]
ok found issue --- didn't create a wallet before ... you can close this issue ....

**Comment by caedesvvv** [comment]
you shouldn't be able to get there before you have created a wallet so I changed the title to reflect the real issue and will keep it open.

thx for reporting!

**Comment by veox** [comment]
I have noticed this behaviour when crash-closing Chromium. After starting it again, the DW tab is open and the first identity is open (I have two, `veox` and `veox-testnet`). Just as in OP's screenshot, the identity selection button (top right corner) is not present.

However, this is not reproducible. :/
