### ISSUE TITLE
Making way for localizations + language selection in Settings

### ISSUE THREAD

**Issue by leafcutterant** [darkwallet/darkwallet#69]
As the title says. Once done, I'm willing to contribute a translation to my native language and maintain it.

**Comment by dabura667** [comment]
me too (Japanese)

**Comment by sembrestels** [comment]
I like that enthusiasm! We are going to implement localization support soon, but we won't request translators since we'll be in beta stage, because in that moment is when we'll have all the strings there, ready to translate.

You'll receive notices soon! Thanks for the collaboration!

**Comment by dabura667** [comment]
May I suggest crowdin.net I have used them with translating Electrum, Multibit, and Mycelium... very great for open crowd sourced localization.

**Comment by leafcutterant** [comment]
+1 for crowdin.net!

**Comment by HostFat** [comment]
There is also transifex.com.
I'm not saying that it's better, just to see every possibility ;)

**Comment by sembrestels** [comment]
+1 for transifex, it is open source.

**Comment by leafcutterant** [comment]
+1 for everything open source.

**Comment by caedesvvv** [comment]
done by the recent merge of the translate branch
