### ISSUE TITLE
Switch to using 'bits' instead of BTC

### ISSUE THREAD

**Issue by genjix** [darkwallet/darkwallet#70]
https://bitcointalk.org/index.php?topic=592691.0

http://blog.bitpay.com/2014/05/02/bitpay-bitcoin-and-where-to-put-that-decimal-point.html

**Comment by sembrestels** [comment]
Shouldn't it be coordinated with the rest of community? If we are the only wallet that use bits, it will be confusing.

I've talked with @caedesvvv to do it smart: if you have >=1 BTC in a pocket, the price appears in BTC, else if you have >=1 mBTC, in millibitcoins...

We considered the following units: bitcoin, millibitcoin, dorian and satoshi.

**Comment by ABISprotocol** [comment]
I find this to be a perplexing question, but I'd use this wallet no matter what way you were to set it:  However, my first preference would be that it would be to be set so that the user could set it so that it would appear however the user would like it to appear.  Max. voluntary.

**Comment by caedesvvv** [comment]
it can be another option like we have with mBTC now, but yes the best in many situations is show appropriate humanized unit that depends on how much you actually have since in our experience it's annoying when you have pockets with mbtc and say multisigs or other pockets with btc.

**Comment by leafcutterant** [comment]
I agree that bits should be included, but it should be default only by opting in. Settings could have BTC, mBTC, bits, satoshis and a smart option where the wallet uses the most human-readable based on the number (this would be the default).

If I get it right, bits and dorians are the same (10^(-6) BTC). I think bits are better and shorter, not to mention Dorian has already had enough unwanted attention.

**Comment by rdymac** [comment]
To represent micro-bitcoins I like 'mikes' instead of 'bits'. Gavin Andresen seems too http://www.reddit.com/r/Bitcoin/comments/24m3nb/disliking_the_word_bits_does_not_mean_favouring/ch8gw04?context=3

**Comment by leafcutterant** [comment]
Mikes? Named after whom? Mike Hearn? Regardless of origin, mikes sounds somewhat laughable and shows no relation, while bits express shortly and concisely that it's the name for a small amount.

**Comment by rdymac** [comment]
@leafcutterant Why would it need to be after someone? micro > mic > mike it is derived from the sound. Bucks origin came after a name too?

**Comment by DobZombie** [comment]
I think "bits" should be left out until it becomes a community standard.  Any changes to the way a wallet represents bitcoin can confuse and scare off new users.  IMO of course :)

**Comment by leafcutterant** [comment]
Wow @rdymac , silly me, micro -> mike didn't occur to me. I don't know. I still like bits better, but just my preference ;) Maybe @DobZombie is right, BTC should be left as the default and have mBTC, bits/mikes, satoshis and the "smart option" as opt-in.

**Comment by rdymac** [comment]
I agree it should be an option not enabled by default, but many sites and wallets are enabling mBTC as default (with the BTC optional)...

**Comment by martindale** [comment]
Hey guys, Eric with @bitpay here... I've just added a configuration option for this in #130.  Cheers!

**Comment by caedesvvv** [comment]
closing since we have bits support and won't be setting it as default, will favour auto mode but it's not properly developed yet.
