### ISSUE TITLE
bug?  can't install

### ISSUE THREAD

**Issue by rodancap** [darkwallet/darkwallet#72]
I am getting the following error message when attempting to load the unpacked extension: 
Could not load extension from '/home/downloads/darkwallet-0'. Manifest file is missing or unreadable.

my chrome is set to unicode utf-8
tried chromium as well to no success
Linux Debian Stable Wheezy

**Comment by sembrestels** [comment]
It's not a bug, we are also with Debian. Maybe chrome haven't read permissions in the folder (it sometimes happens when unzipping).

**Comment by rodancap** [comment]
ok, thanks for the tip. I unzipped it again using xarchiver instead of squeeze and now it's installed.
