### ISSUE TITLE
Large unit causes text overflow on Pocket history tab.

### ISSUE THREAD

**Issue by dabura667** [darkwallet/darkwallet#73]
![bug](https://cloud.githubusercontent.com/assets/6586275/2870275/088285c8-d2ba-11e3-82d7-03c6e934a69c.PNG)

The unit in question is mBTC. It only seems to overflow when shown in the parenthesis of the unconfirmed balance.

**Comment by dabura667** [comment]
Note: The overview tab has the right parenthesis like exactly almost touching the black outside of the grey. So while it's barely in bounds, it still looks bad.

I suggest aligning the last digit of the decimal (or integer) with the last digit of the Total. (in the case of the above image, lining up the 2 in .85192 with the 0 above it.)

**Comment by tilthz** [comment]
can you check with latest?

**Comment by tilthz** [comment]
this should be fixed now. please reopen if it still happens.
