### ISSUE TITLE
Suggestion: Disable animations option.

### ISSUE THREAD

**Issue by dabura667** [darkwallet/darkwallet#75]
Enable the ability to disable animations or set their speed or something. clicking through get's tedious when you want to get somewhere quick.

Probably planned, but just posting just in case.

Also wondering if hotkeys are planned?

**Comment by rolfvreijdenberger** [comment]
+1 on this, some ui specific settings would be nice

**Comment by veox** [comment]
Already implemented: https://github.com/darkwallet/darkwallet/commit/c1a595d6bbeaecc1817e8dfea88321690171d5ad
