### ISSUE TITLE
Problem creating a new wallet

### ISSUE THREAD

**Issue by davidam** [darkwallet/darkwallet#8]
The problem is that when I've written the new seed again and I accept, it does nothing. I has been tested 6th February of 2014.

**Comment by caedesvvv** [comment]
get a fresh clone of the repo, then do:
git submodule init
git submodule update

then try, if there are problems, you need to post here the javascript errors (ctrl+shift+j).

**Comment by davidam** [comment]
Thanks! The tool is exciting, perhaps I can help you in some issue.
