### ISSUE TITLE
The Android Schildbach wallet cant seem to read the qr codes generated by dark wallet

### ISSUE THREAD

**Issue by IfThenElsewhere** [darkwallet/darkwallet#81]
Using a note 3 Schildbach Wallet version 3.44

I can read every other qr code with it but not the ones displayed by darkwallet

**Comment by tilthz** [comment]
does the same phone scan using, say, mycelium or barcode scanner?

**Comment by IfThenElsewhere** [comment]
Mycelium works and so does Barcode scanner

**Comment by genjix** [comment]
the qr codes need bitcoin: before them. some wallets are fine without it, but standard is to include uri prefix

**Comment by IfThenElsewhere** [comment]
Mycelium works and so does Barcode scanner

**Comment by IfThenElsewhere** [comment]
Sorry this posted twice accidentally, yeah maybe that's what it is. Is the qr code working with other people using the android wallet?

**Comment by tilthz** [comment]
Confirmed not working here. the bitcoin: prefix does not solve it. Use mycelium for now i guess.

**Comment by rdymac** [comment]
Not working either with a really reliable QR code scanning app that reads almost any QR code I've seen. Even customized ones with images in it.

EDIT: Also when having created a multisig and going to Fund > Script, the QR is not generated and the Script number is shown instead.

**Comment by leafcutterant** [comment]
I tried stealth address QR codes with CodeTwo QR Code Desktop Reader (on desktop, understandably) and it can't read it. Neither can QuickMark for Desktop.

http://www.onlinebarcodereader.com/ can't read it.
http://zxing.org/w/decode.jspx CAN read it. It's an open source project. Maybe you should look into their code.

**Comment by tilthz** [comment]
Sucessfully tested working in Schildbach wallet.
