### ISSUE TITLE
CoinJoin transactions not being randomized

### ISSUE THREAD

**Issue by petertodd** [darkwallet/darkwallet#82]
Doesn't look like the order of inputs and outputs is being randomized; let's fix this!

**Comment by petertodd** [comment]
Oh, and a more subtle issue: the opportunistic mixing functionality seems to only mix the amount of the destination txout, rather than the change txout. It should mix both. Example: https://blockchain.info/tx/8e56317360a548e8ef28ec475878ef70d1371bee3526c017ac22ad61ae5740b8

See how there are two 1mBTC txouts? The 1mBTC txout was the intended output amount, and it seems that every opportunistic mix that happens only ever copies that intended amount. What should be happening is about half the time the opportunistic mix mixes the change amount, thereby making the ownership of the change in question. This is particularly important with sends to P2SH: https://blockchain.info/tx/812bee538bd24d03af7876a77c989b2c236c063a5803c720769fc55222d36b47

The txout sending 2.5mBTC to 37k7toV1Nv4DfmQbmZ8KuZDQCYK9x5KpzP was copied by a non-P2SH output sending 2.5mBTC to 13uZhwmnuo2tN6HoHoLYCN7PHgbsMaL2az; this isn't really improving privacy. Instead it would have been much better for the opportunistic mixer to mix the change amount, 101mBTC to 14y2MsnC91Bk5b5riAnC6LuJ6CZAzwutzA.

**Comment by caedesvvv** [comment]
Regarding randomization, yep they are not getting randomized even if it did we're not offering guarantees. But ok, I'm adding it.

About mixing change or not change, you're right also we should mix one or the other (i'll add this today also).

But in the p2sh case, why would it not help the privacy? You still don't know which of the two inputs was intending to pay to the p2sh (assuming the outputs where ranzomized).

**Comment by petertodd** [comment]
Thanks.

You do know which input was intended to pay to the p2sh, because only one of them is a p2sh output! That's why the change is the right choice to mix - both change addresses are pay-to-pubkey-hash.

**Comment by caedesvvv** [comment]
hmm i dont follow, how would you know A was originally paying to p2sh and not B? (maybe I'm overlooking something). Also later you can't take for granted someone is not paying to some p2sh as part of their offering in a mix even if they didn't initiate, could even be their "change"

**Comment by petertodd** [comment]
Ah, yeah, I see you're point. You are correct in that the source of the funds is randomized just fine; I was thinking about how it's optimal if the funds leaving the transaction are optimally unknown as well.

**Comment by genjix** [comment]
btw what do you guys think of splitting amount based on powers of 2 (when split_amount > fee)? suggestion by phantomcircuit.

**Comment by genjix** [comment]
i.e A sends 4.6 BTC and B sends 2.2 BTC:

Amounts for A: 4, 0.4, 0.2
Amounts for B: 2, 0.2

**Comment by petertodd** [comment]
@genjix I don't think that's needed given that the counter-parties in CoinJoin transactions are, right now, people just mixing funds in general and copy the output amounts of the other user. Maybe implement that in the future, but for now I'm inclined to keep things simple and low-cost. (more outputs == more fees after all)

**Comment by caedesvvv** [comment]
i was thinking in the lines of splitting more to provide more equal outputs

**Comment by genjix** [comment]
ok

**Comment by DobZombie** [comment]
Can we have 2 options? Such as... 
1) How many CoinJoin Transactions to perform?
2) Mix the Output, the Change, or both?
Then a box to tell you how much in transaction fees it will cost.

What do you all think?

**Comment by petertodd** [comment]
@DobZombie I'm very inclined to keep things simple for now. Anyway, specifically mixing the change vs. output actually doesn't make sense: why should the other party in the CoinJoin even know which one is change and which one is output?

@caedesvvv @genjix Oh, also looks like outputs in normal transactions aren't being randomized either - we should fix that.

**Comment by caedesvvv** [comment]
Ok, applied the following two changes that should close this task: https://github.com/darkwallet/darkwallet/commit/7f4afc7848f715bd51382be8fa2c824bd4aac83b https://github.com/darkwallet/darkwallet/commit/a1c83bb921734324eb2839464f41d2bf2b7e689a

The first makes the join sometimes happen over the change sometimes over the destination. Also randomizes inputs and outputs keeping stealth nonces together :-P

**Comment by caedesvvv** [comment]
@petertodd: also: https://github.com/darkwallet/darkwallet/commit/7a79913e2afd2f071b2a0a47868af354f4af3f69

that randomizes where the change goes among the outputs when any tx is being built for sending.

**Comment by ABISprotocol** [comment]
The question, my friends, is not if random, but how random.
