### ISSUE TITLE
Addresses generated from Stealth Transactions can not be restored from seed without centralized (potentially malicious) server.

### ISSUE THREAD

**Issue by dabura667** [darkwallet/darkwallet#83]
The ideal method of retrieving the necessary pubkey-of-sender would be from the blockchain directly.

Currently, the server itself (the Dark Wallet server) holds a lookup table that points to the blockchain, but is in no way guaranteed to be tamper-proof.

From my understanding (correct me if I'm wrong) a malicious server (or even a benevolent server that was discretely hacked by a malicious party) may delete entries in the lookup table, preventing the client from recovering the information needed to generate the private key to that transaction's address.

Considering the nature of Dark Wallet, I think that this should not (and I assume will not) be final spec for the stealth address functionality. If I were a target, Three Letter agencies would love it if my seed no longer had the ability to recover funds sent to me by Stealth Address. This worries me.

I would like to ask if there are currently any plans to remedy this issue. Or, if there is some aspect of the system I am overlooking which guarantees to a large percentage that I will always be able to restore all stealth transactions from seed and seed alone.

**Comment by petertodd** [comment]
1) The lookup table is based on public information - the blockchain - and can be regenerated by anyone. In short, anyone can run one of the servers needed by the Dark Wallet javascript to do lookups.

2) A local wallet can implement the stealth address spec as well. I have the beginnings of a reference implementation that I'm working on for this purpose; I'd love to see stealth implemented in Armory. To reduce bandwidth usage techniques like prefix filters are being investigated.

3) With regard to normal SPV clients using Bloom filters have this exact same problem; a full-node peer can lie about what transactions have matched the filter. In the future we'll probably see a soft-fork to implement per-block txout index commitments; prefix filters are designed to take advantage of this and make lying about what stealth transactions exist impossible.

**Comment by dabura667** [comment]
The entries on the server are shown in the wiki as being the following:

```
metadata:
  [ version:4 ]
  [ max_header_rows:4 ]
  [ entries_count:4 ]
header:
  [        ...         ]
  [ [ entry_index: 4 ] ]
  [        ...         ]
entries:
  [                              ...                               ]
  [ [ prefix_bitfield:4 ][ ephemkey:33 ][ address:21 ][ tx_id:32 ] ]
  [                              ...                               ]
```

Whereas the info implanted into the blockchain in OP_RETURN is the following.

```
OP_RETURN <version:1=6> <nonce:4> <P:33>
```

So assuming we don't have the server and we only have the blockchain which only contains 1 version byte, 4 nonce bytes and the pubkey of the sender. Plus the only other stuff in the actual transaction is in no way related to the receiver until he receives the pubkey.

Then how would the receiver be able to restore his funds from the generated addresses only from seed?

If the sender sent the receiver the nonce every single time, and the receiver logged that for every transaction they received, they could look up the nonce... but other than that there is no way to restore the addresses without the centralized server. The prefix bitfield and the ephemkey are not in the blockchain, correct?

The current way it works (my understanding of it) is that they lookup the prefix bitfield on their servers, which then gives them the pubkey + the txid to double check the pubkey against the blockchain.

Without the DW server, I see this as being impossible.

**Comment by petertodd** [comment]
What's on the server is nothing special - it's just an index of publicly available blockchain data. For instance the ephemeral key, ephemkey, is actually the "P" value in the OP_RETURN output. (is that a mistake in the wiki?) As for the prefix bitfield, that's an index derived from blockchain data. I haven't actually looked at that code lately, but I presume they really mean that for a _query_ for a given prefix_bitfield some set of results are returned. Again the wiki might be mistaken there.

**Comment by petertodd** [comment]
BTW it's worth remembering that _all_ SPV clients have this issue - without lookup servers they have no way of getting blockchain data. For instance your Android Wallet needs lookup servers supporting Bloom filter's to filter out just the transactions they are interested in efficiently, and those lookup servers happen to be (almost) any full-node on the network.

**Comment by dabura667** [comment]
Yes, but with SPV clients I can export privkeys at will and import to Bitcoin Core if I wanted to.

With Stealth I do not even KNOW my privkey without finding the pubkey the sender used.

"As for the prefix bitfield, that's an index derived from blockchain data"

If this is true then it can be looked up independently on the blockchain without relying on the DW servers.

Could you please elaborate on how this data is derived from blockchain data?

**Comment by dabura667** [comment]
To simplify my question without getting into semantics:

Imagine DW servers no longer exist and all the recorded DW server data up til now was deleted and no longer existed.

How would someone who deletes their wallet and restores from seed be able to create all of the privkeys from received stealth transactions?

I am not convinced that this can be calculated using only the blockchain data as nothing associates the txids with your stealth address.

**Comment by genjix** [comment]
read the documentation. it is exactly that.
https://wiki.unsystem.net/index.php/DarkWallet/Stealth

if you have questions about how it works you can find me on #darkwallet freenode irc. https://webchat.freenode.net/

**Comment by petertodd** [comment]
> How would someone who deletes their wallet and restores from seed be able to create all of the privkeys from received stealth transactions?

Right now they could recover their funds by setting up an obelisk server locally, installing the darkwallet plugin, and pointing that plugin to their local obelisk server.

In the future I expect to see other clients add stealth address support. Armory and Bitcoin Core already index the blockchain so adding support would be very easy. I'm told Electrum will soon have the right indexes needed to recover stealth outputs as well in the near future, and again, running your own Electrum server is always an option.

See the rest of the documentation for how the prefix filters work, as genjix suggested.

**Comment by genjix** [comment]
i wrote some text: https://wiki.unsystem.net/index.php/DarkWallet/Stealth#Restoring_from_seed

**Comment by dabura667** [comment]
@genjix Thanks so much! I understand now.

You can check your scan_pubkey against every OP_RETURN of the given format and the contained "P" pubkey. Then by calculating the shared secret "c" you can then add Q + cG and check to see if that address matched the address in the spending output.

Thanks for the clarification.

So a malicious server would only have the effect of slowing down the checking process. I would assume that there are checking measures that actually check the txid on the obelisk server to see if all the info matches the entry on the blockchain.

This issue is closed. Thanks everyone.

**Comment by genjix** [comment]
no worries :) cool stuff. about other stuff i don't know. have you got an account on the wiki to edit? tell me the username. we want to open editing on the wiki but there's too many spammers, so we approve accounts now. you can add info and questions there, and we can answer them.

**Comment by dabura667** [comment]
Yeah, I'll make an account eventually. I've been so busy with work I haven't had time to contribute to any bitcoin stuff. Usually I just translate when I have time, but I'm super interested in the DW implementation of Stealth Addresses.

I was thinking of coding Electrum to allow sending to Stealth Addresses, so I wanted to get a complete understanding of how the process worked. If something like my original misunderstanding existed I was going to hold off, considered that seemed to signal a considerable overhaul of the procedure.

Since restoring from seed is already a slightly time consuming process anyways, I don't think adding 3 words to the 12 word seed to add the prefix into the seed itself would be worth the time it saves for restoring.

Glad it was my misunderstanding. Great job, guys!

**Comment by petertodd** [comment]
@dabura667 re: Electrum, please do! Any wallet can support sending to stealth addresses without too much work, and getting that kind of support is key to making them useful.

**Comment by genjix** [comment]
ok we can make an Electrum section too on the wiki if you decide to embark on that, and I can help you out reviewing your work.
