### ISSUE TITLE
Sending from 2 of 2 Multisig gives incorrect notification in status bar.

### ISSUE THREAD

**Issue by dabura667** [darkwallet/darkwallet#84]
```
You have a spend approval request on the "Unsystem" multisig fund
2 out of 5 signatures still needed
```

This is displayed when I click the DW button on chrome... I am sending from a 2 of 2 multisig wallet not 2 of 5.

Also, Multisig is not going through at all, my friend isn't picking up the 1-sign transaction at all.

Note: I am not using coinjoin. I sent through the send window with advanced option coinjoin off.

**Comment by dabura667** [comment]
Also, Additionally, the name of the multisig fund was "MULTI1" not "Unsystem"

**Comment by caedesvvv** [comment]
the message is not yet showing the proper info other than it's a multisig task.

if your friend needs to sign for now you need to go to the fund section, where you should have a task area now, that has the new tx you need to sign and also your friend.

One needs to sign and pass the sig over and the tx to the other one, who can sign, import the other sig and the tx will then be broadcasted.

We're waiting to have lobby communication for contacts till we have avoid manual steps.

**Comment by caedesvvv** [comment]
will fix this soon

**Comment by caedesvvv** [comment]
This should take care of this issue: https://github.com/darkwallet/darkwallet/commit/be473a395c014ed279f964d39e57063894fa9272
