### ISSUE TITLE
Importing multisig from clipboard is confusing

### ISSUE THREAD

**Issue by dabura667** [darkwallet/darkwallet#85]
If you have the script on the clipboard and you click Import Multisig, it shows a window that asks for only a name and shows all the pubkeys.

This confuses people because they copied the script assuming they had to paste it somewhere, then suddenly there's no place to paste it, and they are confused.

I did a double take the first time too, and I understand bitcoin very well.

The UX on this process needs improvement.

Thanks.

**Comment by tilthz** [comment]
We know. All the UX regarding multisig is being redesigned.

**Comment by ABISprotocol** [comment]
It is also possible that some collaboration at this time with Armory people may be helpful. They are testing their multisig.  See also [here](https://bitcointalk.org/index.php?topic=559776.0) and of course [here](https://bitcoinarmory.com/download/building-armory-from-source/) on source notes re. Armory testing, and for some earlier discussion that you probably have already seen, [here](https://github.com/OutCast3k/bitcoin-multisig/). cc: @OutCast3k

**Comment by caedesvvv** [comment]
This has been reworked already.

**Comment by dabura667** [comment]
Thank you! I assume you are referring to the commit below. (I will link it for future reference)

9987ee626b440e3036c10dc4e683d473f20e66e3

**Comment by ABISprotocol** [comment]
Thank you.
