### ISSUE TITLE
Choosing UI colors and ability to save them as text ("themes")

### ISSUE THREAD

**Issue by leafcutterant** [darkwallet/darkwallet#86]
Some freedom would be beneficial to customize UI colors. I suggest
1. unifying color usage across the whole app (mainly between Settings - Lobby - rest of the app).
2. placing color options (fold-out RGB pickers) in Settings for the values.
3. adding ability to export it as text, this way you'll have "themes".

**Comment by dabura667** [comment]
+1

I would love to personalize! This sounds like a good low priority idea.

**Comment by genjix** [comment]
+1

would bring lots of dev to UI front

**Comment by tilthz** [comment]
Customizing colors or making color themes is easy. Just fork/swap the app.css file (people serious about this should compile the SCSS when making changes instead). We might make a light theme or let users choose colors from the settings UI in the future, but I don't think it's gonna make dev stuff any easier in the UI front. Quite the opposite, unless we had a sudden influx of people making significant contributions in the UI.

**Comment by tilthz** [comment]
How to make a "theme":

1) Clone the repo
2) run "npm install"
3) run "bower install"
4) run "grunt"
5) edit the app.scss file as you like, grunt will compile to css
6) load the darkwallet in chrome to see how it looks

When we approach stable I will make it easier to theme it (using just scss variables), and maybe we'll think about "official" theme support. Closing this for now.
