### ISSUE TITLE
Sometimes 'Create wallet' button is missing

### ISSUE THREAD

**Issue by SimonJester** [darkwallet/darkwallet#89]
I can only reproduce this behavior inconsistently (maybe 25% of the time).

Steps to reproduce:
- OS: Windows XP
- Browser: Chrome 34.0.1847.131 m
- DarkWallet: 0.1.0
- Open multiple browser tabs
- Press the DarkWallet button -- but do NOT press "Create wallet"
- Close the current browser tab
- Press the DarkWallet button. Wait about ten seconds.

Actual results:
The DarkWallet dropdown remains blank (has no "Create wallet" button).
Clicking on the blank dropdown does nothing.

Expected results:
Interacting with other aspects of the browser should not prevent the DarkWallet dropdown from working.

Workaround:
Opening a new browser tab and closing existing tabs seems to restore the dropdown.
Also, exiting Chrome and re-launching works.

I have also seen the following actions cause this behavior as well:
1. Use the browser normally for a while, open a new tab, press the DarkWallet button.
2. Or, click repeatedly on the DarkWallet button.

![dw_blank-create-wallet-dropdown](https://cloud.githubusercontent.com/assets/157191/2896119/a84f7ca4-d568-11e3-845b-c6b7e647a693.png)

**Comment by wksantiago** [comment]
In my windows 8.1, chrome wallet I get same blank windows but If I keep trying it appears and is normal.

**Comment by dabura667** [comment]
I get this frequently on Windows 7. the second time I click it usually comes up fine.

**Comment by SimonJester** [comment]
One other thing, I originally saw this behavior _before_ I created my first wallet.

**Comment by dabura667** [comment]
This is a valid issue, why did you close it?

**Comment by SimonJester** [comment]
Why did this get closed? I was trying to add a comment.

**Comment by millsdmb** [comment]
I had experienced this when running the alpha build, but once i switched to run the latest developer version, i notice this barely if at all. Maybe ~10% of the time. I presume it has to do with periods of connectivity loss with obelisk or the gateway.

edit: just got one now. connected to both servers "OK".

![image](https://cloud.githubusercontent.com/assets/7471116/2906390/4a714a92-d610-11e3-8a78-2dee813525b6.png)

**Comment by millsdmb** [comment]
now that button is SLICK! You guys rock
