### ISSUE TITLE
When sending funds if wrong "unlock password" then there is no feedback from the GUI

### ISSUE THREAD

**Issue by wksantiago** [darkwallet/darkwallet#90]
When sending funds if wrong "unlock password" then there is no feedback from the GUI.
It just does not do anything.  It would be good to provide feedback to user that the wrong password was entered.

Thanks,

**Comment by wksantiago** [comment]
If its closed is it because the has been fixed?

**Comment by millsdmb** [comment]
yupp! added to https://github.com/darkwallet/darkwallet/commit/11c74df59fb2a690a7d8eba748b17081b9eafe18

now shows 'Password incorrect!'

**Comment by wksantiago** [comment]
so this change is not included in v-0.1.0?

**Comment by dabura667** [comment]
Download latest ZIP from the git home page and replace your 0.1.0 folder with it. That will update your software. Your wallet files are not stored in there, so your wallets will be fine. (You shouldn't be using DW with real btc anyways)

**Comment by wksantiago** [comment]
Perfect it work great thanks for the information dabura667

Great work Cheers,
