### ISSUE TITLE
When enabling Coinjoin on a pocket, incorrect password yields no response

### ISSUE THREAD

**Issue by millsdmb** [darkwallet/darkwallet#94]
![image](https://cloud.githubusercontent.com/assets/7471116/2910801/6bab6eae-d64c-11e3-9d3f-0d25ac0f70f9.png)

wrong password entered, only result is an unchecked "Mix Funds on this Pocket" box.

**Comment by wksantiago** [comment]
If you press OK with the wrong password the UI does not tell you that it was an incorrect password.

**Comment by wksantiago** [comment]
I downloaded the latest Pre-release ( 0.1.0 - f8824f8) again today and still when sending and entering the prong password the UI does not provide feedback. Am I downloading the wrong version that is getting updated?

**Comment by millsdmb** [comment]
get it from
https://github.com/darkwallet/darkwallet/archive/f8824f8f51f34564c1c823dc25ebd7c735062bcb.zip

Regards,
Matt Milsap
203.837.6743 (mobile)

**Comment by wksantiago** [comment]
Thanks Matt

On Thu, May 8, 2014 at 10:25 AM, millsdmb notifications@github.com wrote:

> get it from
> 
> https://github.com/darkwallet/darkwallet/archive/f8824f8f51f34564c1c823dc25ebd7c735062bcb.zip
> 
> Regards,
> Matt Milsap
> 203.837.6743 (mobile)
> 
> On Thu, May 8, 2014 at 10:22 AM, wksantiago notifications@github.comwrote:
> 
> > I downloaded the latest Pre-release ( 0.1.0 - f8824f8<
> > https://github.com/darkwallet/darkwallet/commit/f8824f8>)
> > again today and still when sending and entering the prong password the
> > UI
> > does not provide feedback. Am I downloading the wrong version that is
> > getting updated?
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/darkwallet/darkwallet/issues/94#issuecomment-42555554>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/darkwallet/darkwallet/issues/94#issuecomment-42555957
> .

## 

William K. Santiago, VCP5
716-222-0886
@williamsantiago
william@wksit.com
LinkedIn: http://www.linkedin.com/in/wksantiago
www.wksit.com
Public OpenPGP key:
Herehttp://sks.research.nxfifteen.me.uk/pks/lookup?op=get&search=0x4E99E8C2094C93EC
