### ISSUE TITLE
Receiving stealth in pocket beyond first does not display it in the UI

### ISSUE THREAD

**Issue by veox** [darkwallet/darkwallet#95]
Note: this is after https://github.com/darkwallet/darkwallet/commit/b708f341e3c481d81e4cfff51ecb0a7a6233277a

The tx is detected by DW (shows in the console), but not in the UI. there is no notification, and no changes of balance, including after 6 confirms.

Will update with more details.

**Comment by caedesvvv** [comment]
ok, investigating this.

that commit fixed stealth addresses being put all into the first pocket. may have broken there or maybe it's something else we're overlooking.

**Comment by veox** [comment]
Using `darkwallet 0.1.0-125-g6769cfa`.

Steps to reproduce:
- create two chromium users (_sender_ and _receiver_), both with DW and an identity for testnet;
- for both users, click Settings->Tools->Development->Receive Stealth, and restart chromium ([just in case](https://wiki.unsystem.net/index.php/DarkWallet/Alpha/KnownIssues#Bug_receiving_stealth_in_pockets_beyond_the_first));
- send from _sender_ to _receiver_'s first pocket's ("spending") stealth address (without CoinJoin);
- wait for tx to be mined;
- _receiver_ sees incoming tx in both console and UI (not in DW button, but that's a separate issue);
- send from _sender_ to _receiver_'s second pocket's ("savings") stealth address (w/o CJ);
- wait for tx;

Expected result:
- tx shows in both _receiver_'s console and UI.

Actual result:
- tx is either not detected, or shown in console only (2 issues compounded?..).

Sorry, this was a little more reproducible yesterday. :(

**Comment by caedesvvv** [comment]
Ok, checked in dev version, and I saw the problem is it wasn't scanning properly for pockets after the first due to a cache we're having so we don't check twice the same stealth rows (atm obelisk is returning not just from height we ask but will be fixed soon).

Fixed in (maybe check there's no issue with latest dev if you can): https://github.com/darkwallet/darkwallet/commit/e7f75724d1147a323f54c6728068da91c1139c1e

**Comment by veox** [comment]
Works now: updated DW (EDIT: to `0.1.0-128-ge7f7572`), restarted chromiums, clicked "Receive Stealth" in _receiver_, missing transactions detected. Sent new transactions (2, w/ and w/o CJ), both went through.

Awesome, closing.
