### ISSUE TITLE
Pocket balance panels on All window balance not accurate

### ISSUE THREAD

**Issue by dabura667** [darkwallet/darkwallet#96]
![pic1](https://cloud.githubusercontent.com/assets/6586275/2917902/c915e1ea-d6ca-11e3-9c14-16868f0793f5.PNG)
![pic2](https://cloud.githubusercontent.com/assets/6586275/2917905/cdafbdfc-d6ca-11e3-81c7-a9b0dc53f4d9.PNG)

My balance of about 4 BTC shows in my total balance, but not on the spending pocket panel.

I had the tab open for a while, was using chat fine and the histories all loaded properly. So I don't think it is a server lag issue.

Misdisplay of balance, so I assume "semi-critical" would fit.

Added suggestion:

Having multi-sig be on their own row, or separated somehow. If I didn't know better I would wonder why 4.7BTC spending + 1BTC MULTI1 pocket is not grand total of 5.7BTC?

**Comment by millsdmb** [comment]
![image](https://cloud.githubusercontent.com/assets/7471116/2921384/b17c184c-d6f2-11e3-9828-428bb62775e1.png)

**Comment by dabura667** [comment]
Millsdmb's Total pane is also not showing, hmm...

**Comment by millsdmb** [comment]
This actually does not seem to have resolved my individual balance issue,
I've reset the extension and the browser twice. What else might I try to
ensure it's resolved?
 ​-Matt​

**Comment by caedesvvv** [comment]
sorry i did a second commit with more fixes that's probably what's affecting you have you checked like letst update?

**Comment by millsdmb** [comment]
fixed, and please don't apologize -- I'm just looking to help you guys.

-Matt

**Comment by caedesvvv** [comment]
ok! great :)
