### ISSUE TITLE
Scanning stealth should be offloaded to its own thread (can freeze the wallet for some time)

### ISSUE THREAD

**Issue by letsgetDARK** [darkwallet/darkwallet#97]
Ok here is my small report, Dark wallet alpha 2 is just freezing. Alpha 1 working well.

When i try to switch to a different panel, chrome is not responding. I need to close it.
When i open my browser again it ask me if i want to delete the extension.

I deleted it, redownload, re install. After a couple of freezing, wallet seems to works. But i think it's need to be fixed anyway because it's really look like the wallet is not working at all at first.

**Comment by sembrestels** [comment]
Yes, it is becasue it is scanning the stealth addresses at the beginning. The solution is run it, and maybe also signing and other stuff related with crypto, in its own thread. [WebWorkers](https://developer.mozilla.org/en/docs/Web/Guide/Performance/Using_web_workers) to the power!

**Comment by caedesvvv** [comment]
Should be taken care of by: https://github.com/darkwallet/darkwallet/commit/45b4c2a6963067923ca271793ab4ae0321addc18
